### ISSUE TITLE
[Page: Concepts List] Missing concept blurbs

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#10]
I am not entirely certain if I should report this, but I recall concept tooltips looking 100% ready before, so I was surprised to find that the blurbs and symbols are now missing from them.

<img width="853" alt="Screen Shot 2021-05-15 at 09 45 09" src="https://user-images.githubusercontent.com/7852553/118352778-8dc7bf80-b563-11eb-8033-589df86de318.png">

I have no clue if this is a CSS issue or an ETL issue.

**Comment by iHiD** [comment]
Nice catch. Thanks.
