### ISSUE TITLE
[Profiles: New] The character counter below the Bio doesn't update even if the Bio is updated

### ISSUE THREAD

**Issue by ProProgrammer2504** [exercism/v3-beta#103]
![2021-07-02 (2)](https://user-images.githubusercontent.com/73734376/124216797-a6406900-db14-11eb-9e19-9eb436a35126.png)

While writing a Bio in the `/profiles/new` page, the character counter remains at 0 even if the Bio is updated.

**Comment by iHiD** [comment]
@kntsoriano I wonder if it's worth just making an input component that has the count next to it, rather than turning the whole form etc into React.

**Comment by kntsoriano** [comment]
@iHiD I think it's as easy to make the whole form component to React. It'll also be more flexible once we make this form a bit more complicated.

**Comment by iHiD** [comment]
OK - do that, but keep it a low priority for now. This isn't that important compared to bugs.

**Comment by iHiD** [comment]
@kntsoriano Did you do this? If not, this is one that's, not blocking but would be good soon :)
