### ISSUE TITLE
[Exercises List] Surprising exercise order on a joined track

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#107]
On a track that I haven't joined, the order of exercises is clear to me:
- first, all concept exercises in the same order as in `config.json`
- second, all practice exercises in the same order as in `config.json`

On a track that I did join, I observed those ordering rules:
1. in progress
	1. practice exercises
  		1. and here? what's the sorting on this level?
	2. concept exercises
2. available
 	1. practice exercises
	2. concept exercises
3. published
 	1. practice exercises
	2. concept exercises
4. locked
    1. here's chaos! practice exercises mixed up with concept exercises

First level order by status, second level order by type.

My thoughts and questions about this:
1. What's up with the chaos in step 4.1? Why are practice exercises mixed in with concept exercises? (See screenshot below) Is this a bug?
2. On a track that I have joined, why are practice exercises first? They aren't first on a track that I haven't joined, and they aren't first on the big punch card under "Your Activity" on the tracks page.
3. What is the third-level order logic? E.g. all concept exercises in progress, how will they be sorted?

Here's the chaos from step 4.1:

![Screen Shot 2021-07-02 at 19 28 16](https://user-images.githubusercontent.com/7852553/124313080-a8d0ac00-db70-11eb-9218-54d7e97b1efd.png)

**Comment by iHiD** [comment]
https://github.com/exercism/website/blob/main/app/commands/exercise/search.rb#L30-L39

This is the sorting code. `position` is the order of the config.json. I'll read your issue properly over the weekend :)

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/1198

---

> What's up with the chaos in step 4.1? Why are practice exercises mixed in with concept exercises? (See screenshot below) Is this a bug?

Yes a bug. Fixed in https://github.com/exercism/website/pull/1198

> On a track that I have joined, why are practice exercises first? They aren't first on a track that I haven't joined, and they aren't first on the big punch card under "Your Activity" on the tracks page.

Probably also a bug. They should now (pending merge) be ordered by `iterated` then `started` and within that by concept then practice then within that order in the config.

> What is the third-level order logic? E.g. all concept exercises in progress, how will they be sorted?

###  First level
```
        iterated started
        available
        completed published
        locked
```

###  Second level
1. Concept
2. Practice

###  Third level

Order in `config.json`
