### ISSUE TITLE
[Page: External Track] Swift track Git::MissingCommitError

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#11]
When I am logged in and try to go to Swift's page (I haven't joined the track), I get this 500 error:

<img width="1303" alt="Screen Shot 2021-05-15 at 10 13 15" src="https://user-images.githubusercontent.com/7852553/118353445-8229c800-b566-11eb-8154-8951927ff05c.png">

**Comment by iHiD** [comment]
@angelikatyborska Thanks. 

This is due to https://github.com/exercism/swift/issues/444. I've tagged @ErikSchierboom to push a fix for that. @ErikSchierboom Can you also close this when that is done pls. Thanks :)

**Comment by ErikSchierboom** [comment]
This is now working again.
