### ISSUE TITLE
[Mentoring / Queue] Unable to Load Information

### ISSUE THREAD

**Issue by taiyab** [exercism/v3-beta#112]
![image](https://user-images.githubusercontent.com/5337876/124503439-749dfb00-ddbd-11eb-9612-5e5d9b01dd8d.png)

Works for some profiles, not for others.

**Comment by iHiD** [comment]
I get this all the time @kntsoriano

**Comment by iHiD** [comment]
This should be fixed now. @taiyab pls confirm.

**Comment by taiyab** [comment]
All good ✅

**Comment by iHiD** [comment]
Great :)
