### ISSUE TITLE
[Pages: Tracks] After clicking on one of the enrolled tracks, some tracks throw an error

### ISSUE THREAD

**Issue by ProProgrammer2504** [exercism/v3-beta#113]
I have enrolled in some languages like CSharp, TypeScript, JavaScript, Python, and more. But when I click on the CSharp track, this error was thrown. This same happened with JavaScript and TypeScript.

![2021-07-07 (2)](https://user-images.githubusercontent.com/73734376/124687947-9e593e00-def3-11eb-901b-ebd6bb130b62.png)

Here's a picture of the Browser Console:

![2021-07-07 (4)](https://user-images.githubusercontent.com/73734376/124688555-977efb00-def4-11eb-8276-b67d563c932c.png)

**The last error of `__THREE_DEVTOOLS__` is not important as it is one of the browser extension that I have installed, so it doesn't matter.**

**But when I clicked on the Python track, everything seemed fine and no error was thrown. I also enrolled in some more languages like Dart and Common Lisp and they too worked fine. This error seems to be specific to some languages.**

**Comment by angelikatyborska** [comment]
This happens to me too, only for Elixir. I guess it's because the only track I joined and did learn some concepts on it.
