### ISSUE TITLE
[Editor] Click + hold + move mouse doesn't select text in right column 

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#115]
In the editor, selecting text in the right column is not obvious. The usual method that you use (click, hold down the mouse button and move the mouse) doesn't work. It only works to double-click a text block.

In the code editor itself, selecting text works fine.

I think all usual ways of selecting text should work everywhere on the website, especially in that right column with instructions and test results.

It's crucial to be able to copy the compilation errors and google for them, copy some unknown English words and translate them if you're not a native speaker, or copy and part of the instructions and send it to a friend/mentor asking for clarifications.

![2021-07-08 10 13 17](https://user-images.githubusercontent.com/7852553/124888646-94f4d200-dfd6-11eb-908d-158215a7d816.gif)

**Comment by iHiD** [comment]
@angelikatyborska Thanks. I have no idea why this is happening here. It's certainly not intentional!

**Comment by iHiD** [comment]
@kntsoriano The only thing I can think of is that React is intercepting any clicks on the RHS or something. Can you take a look pls? Maybe it's to do with the divider logic? No idea :)
