### ISSUE TITLE
[Exercise/Overview] "You've unlocked X exercises" - too many exercises?

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#119]
I feel like there's something wrong with the logic that counts and displays "You've unlocked X concepts/exercises" on the exercise overview page, but I find it hard to describe what the actual behavior is.

What I would expect form this page is that:
- the count of concepts and exercises in the sentence is always equal to the count of concepts and exercises displayed below the sentence
- the "concepts" that I unlock by doing a specific concept exercise that teaches concepts A & B are a sum of all the concepts taught by concept exercises that: 
	- have concepts A and/or B in prerequisites
	- have all of their other prerequisites already unlocked
- the "exercises" that I unlock by doing a specific concept exercise that teaches concepts A & B:
	- have concepts A and/or B in prerequisites
	- have all of their other prerequisites already unlocked

This means that I would NOT expect to see there exercises that I happen to have available because I did them in v2 or in independent mode of v3, but I didn't actually unlock their prerequisite concepts yet.

Now, here's an example of why I am confused. After completing a concept exercise, I got this modal. The modal shows exactly what I would expect: the next concepts that I just unlocked and their concept exercise. After the modal, I go back to the exercise overview page and I would expect to see exactly the same concepts and exercises that I unlocked. Instead, it says there's 13 unlocked concepts even though it shows only 3, and then 70 unlocked exercises? That makes no sense, on the list of exercises are exercises whose prerequisites I did not unlock yet, eg. strings for "forth" and "phone number".

![Screen Shot 2021-07-10 at 16 14 05](https://user-images.githubusercontent.com/7852553/125192246-1eaad680-e247-11eb-8ae8-0e1b52039eb9.png)

![Screen Shot 2021-07-10 at 16 14 27](https://user-images.githubusercontent.com/7852553/125192248-223e5d80-e247-11eb-9d1d-d06f59dfec11.png)

Here another example of a different concept exercise, again the count is wrong and somehow "Bob" shows up even though it also requires (still locked) strings:

![Screen Shot 2021-07-11 at 12 39 52](https://user-images.githubusercontent.com/7852553/125192271-4306b300-e247-11eb-83e7-c2db71177e4b.png)

**Comment by ErikSchierboom** [comment]
@angelikatyborska This should hopefully be fixed in https://github.com/exercism/website/pull/1234

**Comment by angelikatyborska** [comment]
This is still not true:

> This means that I would NOT expect to see there exercises that I happen to have available because I did them in v2 or in independent mode of v3, but I didn't actually unlock their prerequisite concepts yet.

Are my expectations wrong?
