### ISSUE TITLE
Ruby Concepts Ostruct leads to JSON Parse Error

### ISSUE THREAD

**Issue by Whatapalaver** [exercism/v3-beta#12]
I’m logged in and on the Ruby concepts page. Clicking on OStruct leads to a JSON parse error. 

An empty string is not a valid JSON string.

**Comment by iHiD** [comment]
Thanks 🙂  Individual concept pages aren't currently [in scope](https://github.com/exercism/v3-beta#pagesflows-ready-for-testing) for the beta. 

I'm going to close this for now, but once Concept Pages are in scope, please do check again and reopen this if the problem still remains.
