### ISSUE TITLE
[Page: Editor] Rust test runner always reports "An error occurred..."

### ISSUE THREAD

**Issue by wischi-chr** [exercism/v3-beta#121]
It looks like this (or something similar) happened in the past (see #38)

I tried to run the tests again for an exercise I've already solved (just added a space to a comment to force a re-run) and it's no longer passing/working, so it's probably not the code itself.

**Comment by ErikSchierboom** [comment]
We've identified the issue and will be trying to fix it. Thanks for reporting.

**Comment by iHiD** [comment]
Fixed now. Thanks.
