### ISSUE TITLE
[Editor] Pressing tab should insert indentation per track settings

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#122]
In the editor, when I press the tab button, it inserts a tab character. I would expect it to insert indentation as configured in the track, e.g. for Elixir it should be 2 spaces.

Additionally, after I submit the solution and see my iteration, the tab has a different width than in the editor.

![2021-07-14 05 55 38](https://user-images.githubusercontent.com/7852553/125558940-dc51afa8-cc02-4360-85ac-7484e1232a9d.gif)

**Comment by iHiD** [comment]
@kntsoriano @ErikSchierboom Any idea why this has broken?

**Comment by iHiD** [comment]
Deploying a fix. Pls could you see if that's any better?

**Comment by angelikatyborska** [comment]
@iHiD it was fixed 🎉

**Comment by iHiD** [comment]
Brilliant. Thanks for confirming, @angelikatyborska and nice work @kntsoriano :)
