### ISSUE TITLE
While running the tests on an Exercise, the Cancel button does nothing

### ISSUE THREAD

**Issue by ProProgrammer2504** [exercism/v3-beta#123]
https://user-images.githubusercontent.com/73734376/125658321-f291bcca-533f-490e-8366-84863ca64beb.mp4

When the user completes an `Exercise`, and runs the tests, there is a `Cancel` button which does not work.
The tests run anyway even if the `Cancel` button is clicked and the results are shown.

**Comment by iHiD** [comment]
@kntsoriano Could you check what needs to be done on this pls, do any thing client-side that needs doing for it, and let me know what needs doing server-side. Thanks.

**Comment by iHiD** [comment]
(@ProProgrammer2504 Thanks for reporting btw!)

**Comment by iHiD** [comment]
This should now be fixed, if you'd like to check and close. Thanks for the report :)

**Comment by ProProgrammer2504** [comment]
Yes, it's fixed and works like a charm!

**Comment by iHiD** [comment]
Great! :)
