### ISSUE TITLE
[Page: Editor] [Rust] Test Result doesn't provide details what failed.

### ISSUE THREAD

**Issue by wischi-chr** [exercism/v3-beta#125]
Currently the result page for the tests just shows "Tests failed" and doesn't show which tests failed exactly:
![image](https://user-images.githubusercontent.com/2495113/126010090-1e58edd1-5448-4238-ae12-7fbc672cce6c.png)

As far as I can tell the backend seems to provide at least some of the information about how many tests there are and which ones failed:
![image](https://user-images.githubusercontent.com/2495113/126010289-9ae107e6-3f8f-4cc8-889d-a17a9e775f6e.png)

Here is an example from the C# track with pretty detailed informations about what failed and why:
![image](https://user-images.githubusercontent.com/2495113/126009864-7e6a56be-6615-46ba-863e-ced1e966ca79.png)

**Comment by wischi-chr** [comment]
Ok just found out that this was already reported in #124 

/closed because duplicate

**Comment by iHiD** [comment]
Thanks!
