### ISSUE TITLE
[Page: Editor] Very minor issue with syntax highlighting

### ISSUE THREAD

**Issue by wischi-chr** [exercism/v3-beta#127]
For some reason some types (like in this case `List<string>`) in C# are colorized differently depending on the side:
![image](https://user-images.githubusercontent.com/2495113/126018214-65076298-c1e4-4af2-8d8c-957fff83fc71.png)

I'm not sure if that's by design or even worth fixing.

Found it here: [https://exercism.lol/mentoring/requests/7b988446-a831-11eb-b069-cd08bd9fe49b](https://exercism.lol/mentoring/requests/7b988446-a831-11eb-b069-cd08bd9fe49b)

**Comment by iHiD** [comment]
This would be one for @joshgoebel.

**Comment by joshgoebel** [comment]
Can C# types have nested `<<>>`?  As in `List<array<string>>` or some such?

**Comment by wischi-chr** [comment]
Yes generics in C# can be nested with arbitrary depth in theory. In practice they are propably no more than three levels deep because the code wouldn't be very readable at that point.

**Comment by joshgoebel** [comment]
Could someone have a look at https://github.com/highlightjs/highlight.js/pull/3289

**Comment by joshgoebel** [comment]
Merged, but won't land until 11.3 though.

**Comment by iHiD** [comment]
Thanks. Mind pinging here when 11.3 releases?

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlight.js/releases/tag/11.3.1

**Comment by iHiD** [comment]
@kntsoriano Fancy this one?

**Comment by joshgoebel** [comment]
We may have already bumped the other day, but I'm not following that closely. :)

**Comment by kntsoriano** [comment]
@iHiD Cool. I'll bump HighlightJS.

**Comment by kntsoriano** [comment]
Should be good :) We've previously bumped HighlightJS in this commit: f24d8f9a8b12731ab15e184ae47607afc62ad14e.
