### ISSUE TITLE
[Page: Exercise/Overview] Two different estimated waiting times for mentoring

### ISSUE THREAD

**Issue by wischi-chr** [exercism/v3-beta#129]
Just saw this on my rust track (but I guess it's not rust specific).
On the overview tab it states _"(Median wait time 6 hrs)"_ and on the mentoring Tab _"(Medium wait time ~12 hours)"_

Are those placeholders? At the moment they are formatted differently (font is a bit smaller) on overview, the waiting times are different and there is a typo on the mentoring tab I think (should probably be _"Median"_ instead of _"Medium"_)
![image](https://user-images.githubusercontent.com/2495113/126019086-8e16f6e8-207e-4cd1-9ca1-cd43b4446f2a.png)
![image](https://user-images.githubusercontent.com/2495113/126019092-201660a0-5064-4b05-86bc-2ffad3a4d6bf.png)

**Comment by iHiD** [comment]
They're all placeholders. But they shouldn't be, so we can leave this open :)

**Comment by iHiD** [comment]
Can you comment these out pls:

```
app/javascript/components/student/Nudge.tsx:          <em>(Median wait time {track.medianWaitTime})</em>
app/javascript/components/student/mentoring-session/mentoring-request/MentoringRequestForm.tsx:          start providing feedback. The recent median wait time is ~
app/javascript/components/student/mentoring-session/mentoring-request/MentoringRequestForm.tsx:          {track.medianWaitTime}
app/javascript/components/student/mentoring-session/mentoring-request/MentoringRequestInfo.tsx:            <p>Recent median waiting time: ~{track.medianWaitTime}</p>
```

I'll create a seperate issue that tracks this for adding them back.
