### ISSUE TITLE
Add Toasts to confirm successful actions

### ISSUE THREAD

**Issue by taiyab** [exercism/v3-beta#133]
![image](https://user-images.githubusercontent.com/5337876/126488351-0ecb93bb-64b4-4a3f-a05d-2f47c5c45886.png)

Toasts are temporary and usually used to confirm a successful action.

**Behaviour:** Floating in from bottom centre of screen, float out after 2-3s.

For actions like publishing a solution successfully, changing published iterations, etc.

**Comment by iHiD** [comment]
I've done this. 

@kntsoriano You can set the CSS as `c-toast` with a setTimeout of 4s to remove something to achieve this. (see the Test run cancelled as an example)

**Comment by iHiD** [comment]
@taiyab You can add individual issues for where these should appear if you like, and we'll add them. If they cross page boundaries, they'll be more work to make so we'll probably still hold off on those for a while.
