### ISSUE TITLE
Add table styling for docs

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#136]
https://exercism.lol/docs/using/solving-exercises

**Comment by angelikatyborska** [comment]
Lack of styling is "in scope" for testing? Then I would also like table styling and code snippet syntax coloring in the exercise introductions 🙂 

![Screen Shot 2021-07-22 at 13 54 02](https://user-images.githubusercontent.com/7852553/126635094-a43b4607-d369-4085-b228-99716bec5e06.png)
