### ISSUE TITLE
Add syntax highlight to docs.

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#137]
Lack of styling is "in scope" for testing? Then I would also like table styling and code snippet syntax coloring in the exercise introductions and instructions 🙂 

![Screen Shot 2021-07-22 at 13 54 02](https://user-images.githubusercontent.com/7852553/126635094-a43b4607-d369-4085-b228-99716bec5e06.png)

_Originally posted by @angelikatyborska in https://github.com/exercism/v3-beta/issues/136#issuecomment-884854251_

**Comment by ErikSchierboom** [comment]
This is now working. Check the Python examples on https://exercism.lol/docs/building/markdown/markdown
