### ISSUE TITLE
[Editor] Add syntax highlighting to instructions/introductions

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#138]
Lack of styling is "in scope" for testing? Then I would also like table styling and code snippet syntax coloring in the exercise introductions and instructions 🙂 

![Screen Shot 2021-07-22 at 13 54 02](https://user-images.githubusercontent.com/7852553/126635094-a43b4607-d369-4085-b228-99716bec5e06.png)

_Originally posted by @angelikatyborska in https://github.com/exercism/v3-beta/issues/136#issuecomment-884854251_

**Comment by iHiD** [comment]
@angelikatyborska This seems to work already for Ruby. So maybe it's something that's broken for Elixir. Got a link of somewhere we can check pls?

**Comment by angelikatyborska** [comment]
@iHiD It's only broken in the editor, it works on the concept page and the exercise page. So you need to join the track and start any exercise in the editor, for example lasagna https://exercism.lol/tracks/elixir/exercises/lasagna/edit

![Screen Shot 2021-07-22 at 15 39 44](https://user-images.githubusercontent.com/7852553/126648859-ea857ce6-abe7-44c5-8033-e38b85ed9f4f.png)

**Comment by angelikatyborska** [comment]
It doesn't work for Ruby either:

![Screen Shot 2021-07-22 at 15 43 14](https://user-images.githubusercontent.com/7852553/126649115-247f793e-0ae0-4f78-8127-90d8e4d18745.png)

**Comment by iHiD** [comment]
Ah - ok thanks.

**Comment by iHiD** [comment]
@kntsoriano Can you check this as part of your editor refactor pls.

**Comment by iHiD** [comment]
@angelikatyborska This one should be done now.

**Comment by angelikatyborska** [comment]
Yay, it is 🎉
