### ISSUE TITLE
[Page: Editor] {Safari} Test results look slightly "off"

### ISSUE THREAD

**Issue by joshgoebel** [exercism/v3-beta#14]
<img width="488" alt="Screen Shot 2021-05-17 at 8 33 09 AM" src="https://user-images.githubusercontent.com/6473/118504930-f21c8780-b6f9-11eb-984d-46c4a33e6ef7.png">

Not sure what this is supposed to look like, but it's a bit off looking now.

Per Jeremy:

> Looks like summary elements don't style well in safari!

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/973
