### ISSUE TITLE
[Editor] Practice exercise test suite lacks syntax highlighting

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#141]
The "tests" tab of a practice exercise looks unfinished. It lacks styling and syntax highlighting.

<img width="1111" alt="Screen Shot 2021-07-25 at 12 00 48" src="https://user-images.githubusercontent.com/7852553/126895308-f86c08c8-cae5-4261-b4ee-eea411cbf3e4.png">

**Comment by iHiD** [comment]
@kntsoriano Can you let me know what I need to do, and what you need to do for this pls?
