### ISSUE TITLE
[Editor] When starting a completely new exercise, scroll position is not reset

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#143]
I have been going through multiple learning exercises, one right after the other. Every time I start a new learning exercise in the editor, I have to scroll back up to the beginning of the introduction because the scroll position from the previous exercise solving is remembered.

The gif I recorded is too big to be uploaded here so see https://exercism-team.slack.com/archives/C016Q9KEQ91/p1627222503057700

**Comment by iHiD** [comment]
This should now be fixed by exercism/website#1381 - please could you confirm once it's deployed (30mins or so)

**Comment by angelikatyborska** [comment]
It looks to me like now the RHS of the editor always is always scrolled to the top when I open the editor, which is what I would expect 👍

**Comment by iHiD** [comment]
Great. Thanks!
