### ISSUE TITLE
[Concept List] Visual differences between not logged in and logged in

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#150]
This is how a concept looks like when I am not logged in:

![Screen Shot 2021-08-04 at 16 16 26](https://user-images.githubusercontent.com/7852553/128197332-1e669e8b-c998-47c9-b757-28f85079b857.png)

The learning exercise has a lightbulb.

This is how a concept looks like when I am logged in:

![Screen Shot 2021-08-04 at 16 16 07](https://user-images.githubusercontent.com/7852553/128197460-c00538f8-3d20-4d97-9a6e-79a02e7462f7.png)

The learning exercise has no lightbulb, but practice exercises have locks.

I am not sure if practice exercises should also have locks when I am not logged in, but I am sure that the learning exercise should always have the lightbulb.

Btw. there's also this CSS issue, compare hovering over a practice exercise when not logged in and logged in:

![Screen Shot 2021-08-04 at 16 20 43](https://user-images.githubusercontent.com/7852553/128198000-19e1d2f5-ce68-4ce0-b90e-05b745002461.png)

![Screen Shot 2021-08-04 at 16 20 05](https://user-images.githubusercontent.com/7852553/128198014-1a21568d-1cfb-41ec-93bc-3e5fcb52b14f.png)

There's some weird extra box shadow when logged in.

**Comment by iHiD** [comment]
Thanks :)

Fixed lightbulb and shadow in https://github.com/exercism/website/pull/1380

Things shouldn't be locked externally. I liked Google being able to explore the content and build a nice SEO tree.
