### ISSUE TITLE
[Pages: Profile] When the bio is short, the `Read more` & `Read less` buttons do nothing

### ISSUE THREAD

**Issue by ProProgrammer2504** [exercism/v3-beta#152]
https://user-images.githubusercontent.com/73734376/128300777-5e1d0063-c688-42d0-805d-a025be7ff64c.mp4

When the bio is just a single line, the `Read more` & `Read less` buttons do nothing.

**Comment by angelikatyborska** [comment]
Duplicate of https://github.com/exercism/v3-beta/issues/15

**Comment by ProProgrammer2504** [comment]
Sorry, it was careless of me not looking for previous issues & straight away reporting this. Will try to avoid duplicating issues from next time :) . Closing this one.

**Comment by iHiD** [comment]
@ProProgrammer2504 That's ok! Thanks for closing it, and all your other issues 🙂
