### ISSUE TITLE
[Track] Suspucious student counts: 1, 0, -1

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#154]
I doubt that those numbers are real 🙂 especially because I have joined all of those tracks.
![Screen Shot 2021-08-05 at 14 02 10](https://user-images.githubusercontent.com/7852553/128346720-f83e5ad3-dc0a-4fdd-83ee-07c473c73ec4.png)
![Screen Shot 2021-08-05 at 14 00 08](https://user-images.githubusercontent.com/7852553/128346722-15cbcfc3-ff2b-4ad0-88f5-eb0b87d6049e.png)
![Screen Shot 2021-08-05 at 13 59 52](https://user-images.githubusercontent.com/7852553/128346725-48e7a4aa-7c40-413e-b121-b51f66f168cc.png)

**Comment by iHiD** [comment]
Thanks. I think this is purely an ETL issue. I've just run the bit that's in the latest version of ETL on the current staging DB to test it. Does that look better now? :)

**Comment by angelikatyborska** [comment]
Much better 😀
