### ISSUE TITLE
[Reputation in Header] Dropdown shows the same entry 5 times

### ISSUE THREAD

**Issue by junedev** [exercism/v3-beta#155]
When I click on the reputation badge, I see a correct list. Once I hover over the first item, all items become the same. Video attached. I see the same in Firefox and Chrome (on Ubuntu). After every reload I can see the correct list once. Afterwards always the same-item list.

![broken-rep-dropdown](https://user-images.githubusercontent.com/12543047/128358771-53de15e2-ff07-45d7-873a-eef15806df06.gif)

**Comment by iHiD** [comment]
@kntsoriano Have fun!!

**Comment by angelikatyborska** [comment]
I tried to reproduce this bug (macOS Firefox, Chrome, and Safari). It didn't happen to me for along time. I kept refreshing and dismissing on hover, I must have dismissed at least 50 notifications. Until after some refresh I must have hit some special notification and now it happens to me every time, in all of the browsers.

![2021-08-05 16 25 02](https://user-images.githubusercontent.com/7852553/128366956-1526fed0-3c95-430b-bbe9-51277ccdf744.gif)

**Comment by iHiD** [comment]
@angelikatyborska Can you work out the uuid for that notification? (It'll be in the request that comes back from the server, which should be JSON)

**Comment by angelikatyborska** [comment]
Not of the first one that caused this because it has been successfully dismissed, so I no longer see it.

**Comment by iHiD** [comment]
Oh I see, so now it happens for every notification ever. Funky!! 

@kntsoriano Have fun trying to solve this one! 😉

**Comment by kntsoriano** [comment]
@iHiD Some reputation tokens have outdated `rendering_data`. There have `id` instead of `uuid`. We need to regenerate on production.

**Comment by iHiD** [comment]
Ah! Good man! 2secs.

**Comment by iHiD** [comment]
I've wiped all the caches. Is that better @junedev @angelikatyborska @kntsoriano?

**Comment by angelikatyborska** [comment]
That fixed the issue for me

**Comment by junedev** [comment]
It is fixed for me as well. :tada: :clap:

**Comment by iHiD** [comment]
Thanks all :)
