### ISSUE TITLE
[Track List and Concept Map] Concept count mismatch

### ISSUE THREAD

**Issue by junedev** [exercism/v3-beta#156]
Python shows 62 concepts on the overview page but only 14 on the concept map. Same mismatch for some other tracks (e.g. JavaScript 24 vs. 20).

---

![image](https://user-images.githubusercontent.com/12543047/128359671-2b7aa66b-b6da-4701-a65d-8026a71cdc2d.png)

---

![image](https://user-images.githubusercontent.com/12543047/128359767-a603c75d-c9dd-46a2-8aff-4fb303d8c441.png)

**Comment by iHiD** [comment]
Thanks. I'm guessing this is WIP vs published or similar.

**Comment by iHiD** [comment]
@ErikSchierboom Want to take a look at this one?

**Comment by ErikSchierboom** [comment]
@iHiD Yeah sure.

**Comment by angelikatyborska** [comment]
Other PRs merged 1-2 hours ago were already deployed so I am assuming this one too.

I am still seeing different concept counts, for example JavaScript 26 vs 22:

![Screenshot 2021-08-25 at 15-47-43 Exercism bc1e094f-1e66-4943-b046-bd56409dc792](https://user-images.githubusercontent.com/7852553/130803219-60f4ad02-8c03-4b3a-a094-f39ae2f3d01a.png)


![Screenshot 2021-08-25 at 15-48-01 Exercism f0c8e61b-c124-44bb-80f3-c6101cf41e48](https://user-images.githubusercontent.com/7852553/130803250-ade27e97-ed97-4609-b557-53e2fe7b63da.png)

**Comment by angelikatyborska** [comment]
Yes, thanks 🙂. Sorry, I wasn't aware that you also have to run a script. I try to monitor all issues to check if they are really fixed and sometimes I can't say if the deployment of the fix has been finished already or not 😅

**Comment by iHiD** [comment]
That's fine. I appreciate you keeping an eye on things. I'd not actually realised I needed to run the script, so without your prompt it wouldn't have got fixed on staging :)
