### ISSUE TITLE
[Page: External Track] 'Join the Go track' redirects to sign_up

### ISSUE THREAD

**Issue by andrenbrandao** [exercism/v3-beta#16]
I have found the same behavior in the TypeScript track. If I click on the CTA on the bottom of the page, I can't join the track (it actually redirects to sign_up). The only way is to click on the CTA at the top.

![exercism-join-track](https://user-images.githubusercontent.com/3364098/118565562-caa0db80-b748-11eb-9330-246a83fe8acc.gif)

The button that work is the one below.

![Screenshot from 2021-05-17 19-42-28](https://user-images.githubusercontent.com/3364098/118565597-dc827e80-b748-11eb-8469-3c67b5904674.png)

**Comment by iHiD** [comment]
Great catch. Thank you!
