### ISSUE TITLE
[Docs] V2 track documentation links don't work anymore

### ISSUE THREAD

**Issue by junedev** [exercism/v3-beta#160]
Lots of track documentation contains links like https://exercism.io/tracks/javascript/tests.
Currently those don't work because the new location for these is e.g. https://exercism.io/docs/tracks/javascript/tests (on .lol that would be https://exercism.lol/docs/tracks/javascript/tests). There should be a redirect and/or a bulk PR to fix the links.

Besides the track specific docs, there is also `exercism.io/cli` mentioned in the track documentation that currently doesn't work on .lol. I couldn't find the correct link for this page on .lol yet. Also not sure whether there are more of those Exercism-wide docs link that need to be considered.

**Comment by iHiD** [comment]
Done in https://github.com/exercism/website/pull/1361 - thanks!

The CLI etc ones will get done separately 🙂
