### ISSUE TITLE
Check legacy routes are repointed from v2's config/routes

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#161]
(cc https://github.com/exercism/v3-beta/issues/160, @junedev)

**Comment by junedev** [comment]
https://exercism.lol/cli now redirects to https://exercism.lol/docs/using/solving-exercises/working-locally and the first link in there (installation instructions) currently redirects to https://exercism.io/cli. Could potentially lead to a redirect chain when everything is .io again.

**Comment by iHiD** [comment]
@ErikSchierboom When you're back, can you fix the CLI doc pls. I think the link can probably be removed as the old CLI content is inlined in this doc. We should probably link to the walkthrough in that doc instead for the installation part.

**Comment by ErikSchierboom** [comment]
@iHiD PR opened: https://github.com/exercism/docs/pull/193
