### ISSUE TITLE
"See all [track] exercises ->" link on track page yields "page doesn't exist"

### ISSUE THREAD

**Issue by bobahop** [exercism/v3-beta#166]
On [this page](https://exercism.lol/tracks/rust)

I click "See all Rust exercises ->" and get "The page you were looking for doesn't exist." I get the same for F#.

It looks like the problem is adding the track name after "/exercises", as  [this URL](https://exercism.lol/tracks/fsharp/exercises) works

This is [the bogus URL](https://exercism.lol/tracks/fsharp/exercises/fsharp) from the link

https://user-images.githubusercontent.com/32035397/128563345-5a57cfe4-6d06-47e0-ae7a-f60bd4532b93.mp4

**Comment by iHiD** [comment]
Thanks!

**Comment by iHiD** [comment]
Fixed pending deploy :+1:

**Comment by angelikatyborska** [comment]
Fix deployed, I'll allow myself to close this.

**Comment by iHiD** [comment]
Thanks!
