### ISSUE TITLE
[Page: Profile] Published Solutions do not show code preview

### ISSUE THREAD

**Issue by andrenbrandao** [exercism/v3-beta#17]
In my profile https://exercism.lol/profiles/andrenbrandao the code solutions previews are missing.

![Screenshot from 2021-05-17 19-54-27](https://user-images.githubusercontent.com/3364098/118566293-01c3bc80-b74a-11eb-92de-9c805f3e963f.png)
 
However, in https://exercism.lol/profiles/iHiD they are showing up.

![Screenshot from 2021-05-17 19-54-17](https://user-images.githubusercontent.com/3364098/118566325-1011d880-b74a-11eb-8386-ebee85daa268.png)

**Comment by iHiD** [comment]
Thanks 🙂 

So as an FYI, this is because I've only run though the first 400,000 solutions as I wanted to check they were all right before doing the bulk of them. However, I will at some point process them too.

It's good to leave this issue open though for everyone else wondering the same thing!
