### ISSUE TITLE
[Editor] Markdown parsing bug: paragraph after a block quote

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#172]
I have an exercise (Elixir / City Office) that has a step with this Markdown:

```markdown
## 2. Document filling out fields with blank values

Add documentation and a typespec to the `Form.blanks/1` function. The documentation should read:

> Generates a string of a given length.
>
> This string can be used to fill out a form field that is supposed to have no value.
> Such fields cannot be left empty because a malicious third party could fill them out with false data.

The typespec should explain that the function accepts a single argument, a non-negative integer, and returns a string.
```

This is how GitHub renders it:

<img width="1121" alt="Screen Shot 2021-08-08 at 07 57 17" src="https://user-images.githubusercontent.com/7852553/128622380-080b7cad-41c8-48dd-b87b-653466d88b47.png">

This is how it looks like in the editor. The last paragraph that is supposed to be outside of the block quote gets put into the block quote for some reason:

<img width="748" alt="Screen Shot 2021-08-08 at 07 53 35" src="https://user-images.githubusercontent.com/7852553/128622404-3320068e-dccf-4054-b129-7903a42a9ff6.png">

**Comment by iHiD** [comment]
There's something a little strange happening here.

So if I copy your example above into https://stackedit.io/ I get the same result (it gets put in the blockquote). If I put the raw version in, it seems to not. I wonder if there's some weird hidden whitespace thing. Is this happening everywhere or just in this specific case?

**Comment by angelikatyborska** [comment]
> Is this happening everywhere or just in this specific case?

This is the only usage of a blockquote followed by a paragraph that we have on the track.

> I wonder if there's some weird hidden whitespace thing.

If I select text in the code block in the issue by drag and dropping and copy that, it gets copied without a trailing newline after the end of the block quote. If I use the "copy" button that appears over the code block (not sure if it's a basic GH feature or a browser extension feature) then it gets copied with a newline after the blockquote.

FYI I'm removing the blockquote in favor of a code block in this document anyway, so it's not the highest priority to solve this.

**Comment by Alexander-Taran** [comment]
I've got it the other way. First line of the code block is added to previous paragraph.
Markdown in exercise is ok. But rendering on beta is off.
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/1029452/131254110-a53f42a9-d6dd-4270-9d15-8bee0eb5ccab.png">

Might it be safari on Mac?
I mean the difference between \n an \r\n
