### ISSUE TITLE
[Concepts] Practice exercises aren't ordered like in the config

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#173]
When I browse the practice exercises for a given concept, they are in a seemingly random order. I would expect them to be in the same order as they are in the track's `config.json`. For Elixir, this is important because we sort exercises from easiest to hardest.

For example, for the `cond` concept practice exercise order is:

- zebra puzzle (hardest)
- binary search,
- darts (easiest)
- perfect numbers,
- bob

but it should be:

- darts,
- binary search,
- bob,
- binary search,
- zebra puzzle

<img width="1226" alt="Screen Shot 2021-08-08 at 08 42 12" src="https://user-images.githubusercontent.com/7852553/128623469-51a5e651-d6b5-4c85-a9de-482d4cd01fb6.png">

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/1398
