### ISSUE TITLE
[Contributing/Tasks] Learning exercise vs concept exercise

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#174]
Everywhere on the platform, the term "learning exercise" is used. Only on the tasks page, the filter option is called "concept exercise". In the GitHub repositories and their issues, they're always called  "concept exercises" so maybe it is desirable that the tag on the tasks page is called that too? I'm not sure. But at some point, this switch "learning exercise" -> "concept exercises" needs to happen for a new contributor that used "learning exercises" on the platform, but saw "concept exercises" when they tried to contribute to the track.

<img width="1461" alt="Screen Shot 2021-08-08 at 11 51 17" src="https://user-images.githubusercontent.com/7852553/128628015-d9fcd009-728f-4b38-98e6-1b51a1e827ae.png">

**Comment by iHiD** [comment]
Good point. "Concept Exercise" here should be changed to "Learning Exercise". (@kntsoriano Easy one for you)

**Comment by iHiD** [comment]
Should be fixed now :)
