### ISSUE TITLE
Removing as favourite is broken.

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#176]
https://www.loom.com/share/e1155a79c2f943c2982dbe7c789cfec3

**Comment by angelikatyborska** [comment]
Was a fix deployed? I still can't remove a favorite, but I'm getting a slightly different behavior than on the video. The button stays nice, there's a successful HTTP request but the request doesn't actually remove a favorite:
<img width="1778" alt="Screen Shot 2021-08-18 at 17 26 26" src="https://user-images.githubusercontent.com/7852553/129926481-eab83784-977d-4621-89fa-c905f3f7e096.png">

**Comment by iHiD** [comment]
@kntsoriano :)

**Comment by kntsoriano** [comment]
@iHiD Inside `app/commands/mentor/student_relationship/toggle_favorited.rb`, it prevents marking students as favorites when they haven't had a discussion yet. But our design allows marking students as favorites even if the discussion has not started, what should we do about this?

**Comment by iHiD** [comment]
> But our UI allows marking students as favorites even if the discussion has not started, what should we do about this?

Don't allow this.
