### ISSUE TITLE
Iterations RHS should show a "tests failed" message if tests fail, not a message about automation

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#178]
<img width="1423" alt="Screenshot 2021-08-16 at 22 13 56" src="https://user-images.githubusercontent.com/286476/129630254-6d0b1de9-e083-4f0c-84b5-367af541d3b2.png">

```
irb(main):037:0> s.iteration.status
=> Iteration::Status (tests_failed)
```

**Comment by taiyab** [comment]
![image](https://user-images.githubusercontent.com/5337876/131222701-e14c1154-6277-4069-92b9-39b917a77934.png)

Posted to you in Slack.

**Comment by iHiD** [comment]
@kntsoriano Could you get me a branch going that shows this pls, and then I'll style it tomorrow.
