### ISSUE TITLE
[Page: Editor] Unhandled exception for direct link when not registered for a track

### ISSUE THREAD

**Issue by wischi-chr** [exercism/v3-beta#18]
I'm not sure if this is in scope but couldn't find anything that states the opposite.

I randomly clicked a few links on the beta start page, namely
https://exercism.lol/tracks/ruby/exercises/lasagna/edit

for me this throws an exception
![image](https://user-images.githubusercontent.com/2495113/118643389-c9b98980-b7dc-11eb-97cc-854879037a00.png)

I'm not registered for the ruby track, so I guess that's why it fails.

And here the application stack trace for simple copy/paste
```
app/helpers/react_components/editor.rb:63:in `track'
app/helpers/react_components/editor.rb:9:in `to_s'
app/views/tracks/exercises/edit.html.haml:2
```

**Comment by iHiD** [comment]
Thanks 🙂
