### ISSUE TITLE
[Contributors List] Some list items are not clickable.

### ISSUE THREAD

**Issue by junedev** [exercism/v3-beta#183]
https://exercism.lol/contributing/contributors
If I click on one of the contributors in the list, nothing happens. I would expect to get redirected to the contributors' profile.

Correction: It seems it only happens for some contributors. Probably the ones without public profiles.
Feel free to close the issue if the current state is the intended behavior for now.

**Comment by iHiD** [comment]
1. They shouldn't have chevrons if there's no link (@kntsoriano fix this pls)
2. They should probably have a tooltip saying there's no public profile (I'll tag this bit as an enhancement for me to do in the future)
