### ISSUE TITLE
[Concepts] undefined method `exercise_position' for #<UserTrack::External>

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#187]
When I try to see the syllabus of a track that I haven't joined, I get this error:

![Screenshot 2021-08-19 at 17-57-48 Action Controller Exception caught](https://user-images.githubusercontent.com/7852553/130102124-87924122-a756-4402-a406-bf3cac7e3969.png)

**Comment by iHiD** [comment]
:+1:

Dup of https://github.com/exercism/website/issues/1405

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/1410
