### ISSUE TITLE
Browser tab title contains some hash

### ISSUE THREAD

**Issue by junedev** [exercism/v3-beta#188]
Not sure whether this is just related to the testing environment but I noticed that the title shown in the browser tab contains some hash. Tested in Firefox and Chrome.

![Screenshot from 2021-08-20 15-07-09](https://user-images.githubusercontent.com/12543047/130238080-6af545af-410a-4fa0-8c7d-31a6da4bb423.png)

**Comment by iHiD** [comment]
Yeah - it's intentional. But I'll leave this here as a reminder to make sure it doesn't make it into launch :)

**Comment by iHiD** [comment]
Closed by https://github.com/exercism/website/pull/1535
