### ISSUE TITLE
[Concept Exercise Online Editor]: Using hints should be discouraged

### ISSUE THREAD

**Issue by junedev** [exercism/v3-beta#189]
With the current UI, I feel really encouraged to press "Hints" directly after reading the task.

After clicking the button, e.g. some popup that encourages me to try again without hints with "back to exercise" as primary button and a "reveal" button as secondary button would be great.

![image](https://user-images.githubusercontent.com/12543047/130238863-f4afba4f-d89b-408b-b838-c9a87303b1af.png)

**Comment by iHiD** [comment]
I think changing the button to "Stuck? Reveal Hints" might solve it, and removing the drop-shadow from the button, as a quicker solution. What do you think?

**Comment by iHiD** [comment]
@kntsoriano Can you change the button text to say `Stuck? Reveal Hints` and also change the button style to `btn-default` instead of `btn-enhanced` pls.
