### ISSUE TITLE
[Page: Editor] Exercises list their solution/proof in the example files

### ISSUE THREAD

**Issue by wischi-chr** [exercism/v3-beta#19]
![image](https://user-images.githubusercontent.com/2495113/118643797-4d737600-b7dd-11eb-820d-1ef6b27782bd.png)

Saw that on some typescript exercises, for example here:
https://exercism.lol/tracks/typescript/exercises/two-fer/edit

**Comment by ErikSchierboom** [comment]
This is a temporary feature that allows people to easily test tracks. @iHiD Do we want to keep this?

**Comment by iHiD** [comment]
@ErikSchierboom Yeah. It allows us to quickly move through tracks. I'll mark this as `invalid` but leave it open for others who find it. 

Thanks for reporting, @wischi-chr.
