### ISSUE TITLE
[Journey/Solutions] Filtering solutions partially broken

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#190]
There is something wrong with filtering solutions both by status and mentoring status.

## General

- "Showing X solutions" only shows the numbers of solutions on the first page, not all in total, which makes it feel like filtering is broken because it sounds like those are ALL results, and I know there should be much more.
- 

## Status problems
- I get nothing for "completed" but I have A LOT of completed exercises. I assume "completed" is both "completed published" and "completed not published".
- And I get the same results for "in progess" and "not published (completed)" which doesn't make sense because those two statuses are exclusive.

![Screen Shot 2021-08-20 at 19 14 58](https://user-images.githubusercontent.com/7852553/130270155-5c8d0229-263b-47ca-959f-ddfd4e99d8c6.png)

![Screen Shot 2021-08-20 at 19 15 02](https://user-images.githubusercontent.com/7852553/130270160-4b2ff5f2-9f03-4943-a1bf-c6963888116c.png)

![Screen Shot 2021-08-20 at 19 15 05](https://user-images.githubusercontent.com/7852553/130270172-8930c8a8-3724-4c05-9f07-942a5af99397.png)

![Screen Shot 2021-08-20 at 19 15 09](https://user-images.githubusercontent.com/7852553/130270180-a1df0093-8361-4dbf-a335-0300325de773.png)

## Mentoring status problems

- I get the same results for "no mentoring" and "mentoring completed" which doesn't make sense because those two mentoring statuses are exclusive.

![Screen Shot 2021-08-20 at 19 15 18](https://user-images.githubusercontent.com/7852553/130270100-b544aa2c-afaf-4945-9028-bc4de97ab726.png)

![Screen Shot 2021-08-20 at 19 15 21](https://user-images.githubusercontent.com/7852553/130270122-fec82251-aa96-4f3d-8c9a-013259dd7d2f.png)

**Comment by iHiD** [comment]
@kntsoriano Can you take a look at this pls - I imagine there's a mismatch in expectations between react/rails.

If there are incorrect/missing queries, please tell me, and I'll update those.

**Comment by iHiD** [comment]
(Thanks @angelikatyborska)

**Comment by kntsoriano** [comment]
@iHiD For the exercise status, we have a mismatch between the UI and the API. In the UI, we allow the following exercise statuses: 
![Screen Shot 2021-08-23 at 8 56 41 AM](https://user-images.githubusercontent.com/1901520/130376528-057f3d7b-4633-4b7a-80c9-57b28f2cb086.png)

And in the code:

``` 
enum status: { started: 0, iterated: 1, completed: 2, published: 3 }, _prefix: true
```

Let me know what part (front end or back end) I should change.

**Comment by iHiD** [comment]
Thanks @kntsoriano - I'll take a look at this one and spike a branch up.
