### ISSUE TITLE
[Tracks] "69 languages for you to master"

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#194]
I'm pretty sure that "69" is a placeholder number that needs to be updated to the real one before the launch.

![Screen Shot 2021-08-21 at 17 21 32](https://user-images.githubusercontent.com/7852553/130326550-ebd0b07d-8b74-4910-917c-862275daec15.png)

**Comment by iHiD** [comment]
Fixes https://github.com/exercism/website/pull/1423 (It was a bug, not a slightly-rude placeholder 🙂)
