### ISSUE TITLE
Broken links on https://exercism.lol/docs/building/tooling/test-runners

### ISSUE THREAD

**Issue by bobahop** [exercism/v3-beta#199]
The highlighted links get error pages.

![docs_errors_3](https://user-images.githubusercontent.com/32035397/130336365-687af674-524a-4334-831c-4ccd275538e9.JPG)

This is the error from clicking "creating a Test Runner". the other highlighted links get similar errors. "docker.md" works okay.

![docs_error_2b](https://user-images.githubusercontent.com/32035397/130336383-1ddb5d06-9157-4af5-8898-c5a3b1818cdc.JPG)

**Comment by iHiD** [comment]
@ErikSchierboom I think you were fixing this one already, but maybe didn't push?
