### ISSUE TITLE
[Page: Exercises List] Contributors list does do anything

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#2]
This should link to the contributors list.

<img width="267" alt="Screenshot 2021-05-14 at 14 39 21" src="https://user-images.githubusercontent.com/286476/118278695-2d347600-b4c2-11eb-91cb-1e0dc42d214a.png">

**Comment by angelikatyborska** [comment]
AFAIK this is fixed now

**Comment by angelikatyborska** [comment]
Still works 🎉 I'll allow myself to close this

**Comment by iHiD** [comment]
Thanks!
