### ISSUE TITLE
Broken link on https://exercism.lol/docs/building/tooling/analyzers/comments

### ISSUE THREAD

**Issue by bobahop** [exercism/v3-beta#200]
Clicking "Feedback guidelines" gets a 404 page

![docs_error_4](https://user-images.githubusercontent.com/32035397/130336445-db6219b7-24b5-41a2-af92-4fe1dfa5b0db.JPG)

**Comment by iHiD** [comment]
@bobahop Thanks for this and the others 🙂 

---

@ErikSchierboom These are the guidelines we mentioned last week that we couldn't remember the existence of :) We can change them now to be "friendlier" as the feedback comes from the "analyzer team", not a bot directly.

The link itself here might either need to be fixed (and the file brought over from website-copy probably) or removed. See what you think.
