### ISSUE TITLE
Broken links on https://exercism.lol/docs/building/configlet

### ISSUE THREAD

**Issue by bobahop** [exercism/v3-beta#201]
Highlighted links get Record Not found page

![error_1](https://user-images.githubusercontent.com/32035397/130336641-ff058671-479e-4a12-b83b-0ceba5284e50.JPG)

![error_2](https://user-images.githubusercontent.com/32035397/130336644-ec862c3e-c144-4850-932e-9d4228842e2c.JPG)

**Comment by iHiD** [comment]
@ee7 Want to sort this one? :)
