### ISSUE TITLE
Broken image on https://exercism.lol/docs/building/markdown/internal-linking.md

### ISSUE THREAD

**Issue by bobahop** [exercism/v3-beta#204]
![err_1](https://user-images.githubusercontent.com/32035397/130352828-9597ad2f-e59c-4c25-a6ff-2c851f57bf94.JPG)

**Comment by iHiD** [comment]
@ErikSchierboom Let's chat about how we want to do this. Maybe a GHA script to upload images to s3 like on website-icons.
