### ISSUE TITLE
[Page: Tracks] Joined track shows as unjoined

### ISSUE THREAD

**Issue by jessechounard** [exercism/v3-beta#21]
In the old version of the site I'm on both the C# and Rust tracks, but on V3 only Rust shows up. When I click into the C# track it offers to let me join it like any language I'm not already doing.

Some quick screenshots:
![image](https://user-images.githubusercontent.com/711172/118986144-b32e4200-b944-11eb-927c-3555e58003b1.png)
![image](https://user-images.githubusercontent.com/711172/118986220-c4774e80-b944-11eb-8039-4031b6ed9be7.png)

**Comment by iHiD** [comment]
Thanks for reporting. The ETL data is from about 2-3 months ago. Had you joined C# then?

**Comment by jessechounard** [comment]
Ah, you've got it, I had not. I overlooked that in the readme. Sorry for the false alarm!

**Comment by iHiD** [comment]
Great. And no worries - better to be safe than sorry with ETL! 🙂
