### ISSUE TITLE
[Exercise Icons] No placeholder icon in reputation list

### ISSUE THREAD

**Issue by junedev** [exercism/v3-beta#222]
I just added "Lucky Numbers" as concept exercise in the JavaScript track. There is no icon for the slug yet. The exercise boxes show the correct placeholder icon. However in the reputation list (in the header and on the journey page) there is an empty box instead.

Shows placeholder icon:
![image](https://user-images.githubusercontent.com/12543047/130369359-70b8e579-4100-4388-95d7-5137e69ce0ac.png)

Does not show placeholder icon:
![image](https://user-images.githubusercontent.com/12543047/130369379-a094d818-9bab-4c31-a37b-6d8b3d9242c4.png)

![image](https://user-images.githubusercontent.com/12543047/130369404-5ea3945f-c095-4c8e-a769-a171348f3793.png)

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/1444 - fiddly one this!
