### ISSUE TITLE
[Responsive Header Logged-Out] Elements don't fit on the screen

### ISSUE THREAD

**Issue by junedev** [exercism/v3-beta#223]
On my Samsung Galaxy A6 the Exercism Icon in the header is partly overlapped by the signup button. (Maybe removing the "Explore" text below a certain breakpoint would be a quick fix.)

![20210822_232149](https://user-images.githubusercontent.com/12543047/130370441-8d5c2888-ec3a-4cea-903b-34e3ab91322e.jpg)

**Comment by iHiD** [comment]
Your phone is so small!! :) We're like 50% of the smallest "normal" breakpoint at this stage - I'll add a custom one. Really helpful to see. Thanks :)

**Comment by iHiD** [comment]
I imagine you're going to be the queen of edge-cases for this on that sized screen btw - sorry for all the things you'll find, but the reports will be appreciated! :)

**Comment by junedev** [comment]
Understood, I will click around a bit more and report if I find more things that look broken.

(5'6 inch display isn't really small, for the size of my hands I still find it too big actually)

**Comment by iHiD** [comment]
Yeah - it's more 360px isn't a lot to work with  :)

**Comment by angelikatyborska** [comment]
@iHiD My 4 year old cheap smartphone that I still use because it still works is also 360px wide, just FYI. 720p (1280 x 720) with a 2px density is 360px wide so I'm pretty sure we're not corner cases 🙂

**Comment by taiyab** [comment]
In this instance, we can just add the login/signup buttons into the explore menu.

**Comment by iHiD** [comment]
@junedev @angelikatyborska This look better now?

**Comment by junedev** [comment]
yes, all good now

![Screenshot_20210829-121904_Firefox](https://user-images.githubusercontent.com/12543047/131247019-76d2c2b3-a1cb-4a78-a7bb-bbaa3d78e9a2.jpg)

**Comment by iHiD** [comment]
Great :)
