### ISSUE TITLE
[Track Icons] Icon or placeholder for Factor missing

### ISSUE THREAD

**Issue by junedev** [exercism/v3-beta#225]
![Screenshot_20210823-110434_Firefox](https://user-images.githubusercontent.com/12543047/130429212-a2055f5b-6970-4ff4-a770-cdce25cc25df.jpg)

**Comment by iHiD** [comment]
@taiyab Did this one get missed maybe?

**Comment by iHiD** [comment]
@junedev Should be fixed now :)
