### ISSUE TITLE
[Installation Guide] Overflowing images & buttons

### ISSUE THREAD

**Issue by ProProgrammer2504** [exercism/v3-beta#229]
There are certain images & buttons in the Installation guide of the CLI, which overflow the entire modal

![2021-08-23 (19)](https://user-images.githubusercontent.com/73734376/130452186-2532c976-5a72-4b5d-ae4a-e8a85897cbd8.png)
![2021-08-23 (20)](https://user-images.githubusercontent.com/73734376/130452195-0f030c8e-84f6-41b0-9f51-e90244c864d9.png)
![2021-08-23 (23)](https://user-images.githubusercontent.com/73734376/130452535-8bb758de-72a4-4889-b5b8-2f2f2fad0b08.png)

**Comment by iHiD** [comment]
@ProProgrammer2504 Thanks!

Note to self - this needs `max-width:100%` to images in walkthrough
