### ISSUE TITLE
[Page: Iterations] React breaks with missing tests

### ISSUE THREAD

**Issue by shekari-ah** [exercism/v3-beta#23]
![image](https://user-images.githubusercontent.com/61600246/119001791-88bea200-b9a1-11eb-9e70-d7a4f9db365b.png)

and by clicking on `tests`  the whole iteration part has gone missing 

![image](https://user-images.githubusercontent.com/61600246/119001972-b6a3e680-b9a1-11eb-92f0-9a7615d156a5.png)

**Comment by iHiD** [comment]
Also, please note that this page is currently out of scope too, so please hold off any future bug reports until it is moved in scope.

**Comment by iHiD** [comment]
@kntsoriano I've fixed this in https://github.com/exercism/website/pull/986
