### ISSUE TITLE
[Track] "Reset track" does not work

### ISSUE THREAD

**Issue by junedev** [exercism/v3-beta#230]
When I try to perform "reset track" I see the popup but when I click on "Reset Track" after filling in the text it shows an unstyled "Unable to reset track" error message for a very short time and nothing happens.

**Comment by angelikatyborska** [comment]
When I attempt this, I see this console error and two weird requests without responses. One to `PATCH https://exercism.lol/api/v2/tracks/csharp/reset`, and the other to `POST https://notify.bugsnag.com/`
![Screen Shot 2021-08-23 at 17 44 46](https://user-images.githubusercontent.com/7852553/130477004-6c37fa88-f046-4af9-9ebf-f4341889e7d5.png)
