### ISSUE TITLE
[Page: Log In] Wrong hint in password field

### ISSUE THREAD

**Issue by raghavrkabra** [exercism/v3-beta#236]
In Log In(Sign In) page password field says "Enter your email address" when it should say "Enter your password".

![Screenshot 2021-08-24 at 15-35-26 Exercism 8f722575-17c0-4508-bf8f-e4f86c48ea66](https://user-images.githubusercontent.com/76475203/130598683-c5745232-1e93-4b94-bea7-d911a06aed32.png)

**Comment by iHiD** [comment]
Good spot. Thanks.

**Comment by iHiD** [comment]
Fixed 🙂
