### ISSUE TITLE
[Editor] Old file dialog cuts off end of file; disappears without clicking on it

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#237]
I have a lot of solved Elixir exercises with old files. There's this dialog at the top of the file. Before making a decision on the dialog, I wanted to see the whole file, but it was impossible to do normal scrolling to reach the end of the page. So what I did instead is to press and hold a mouse button inside of the file and then drag it down. That revealed the rest of the file, but when I tried to scroll back up again to see the dialog, it was gone. Reloading the page didn't help.

![2021-08-24 12 20 54](https://user-images.githubusercontent.com/7852553/130600850-22502e86-6f81-4c18-80e8-3040f4a3bc20.gif)

**Comment by iHiD** [comment]
> but when I tried to scroll back up again to see the dialog, it was gone. Reloading the page didn't help.

Can you reproduce this bit on other exercises?

**Comment by angelikatyborska** [comment]
> > but when I tried to scroll back up again to see the dialog, it was gone. Reloading the page didn't help.

> Can you reproduce this bit on other exercises?

I tried a few more exercises and it seems like the dialog is still gone after the first page reload, but comes back after the second and every next page reload for every exercise. It's weird.

https://www.loom.com/share/66b8c0a418dd4c7b8a6d34e616ab4ea9

**Comment by iHiD** [comment]
@kntsoriano I'll fix the CSS for the page scroll, but could you check the disappearing dialog pls?

**Comment by kntsoriano** [comment]
@iHiD The disappearing dialog is also because of the CSS. The div is still there but can't be seen once you scroll down.

**Comment by angelikatyborska** [comment]
I am seeing this issue again

**Comment by iHiD** [comment]
Both, or just the disappearing dialog?

**Comment by angelikatyborska** [comment]
Both, like on that loom video, except that fewer lines are cut off now, it used to be 4, now it's only 2.

**Comment by iHiD** [comment]
Can you see in the CSS what's going on? I think it should be flexbox with the dialog at the top and rest in a scrollable section. I'll try and reproduce again, but my current local setup is fucked so I'm struggling to test things.

**Comment by iHiD** [comment]
Superstar. Thanks. I've pushed a commit. Give it 30mins to deploy.

**Comment by iHiD** [comment]
This should have been deployed now btw.

**Comment by angelikatyborska** [comment]
Yes, it's fixed again
