### ISSUE TITLE
Contributors page query string parameter mismatch

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-beta#242]
On https://exercism.lol/tracks/bash, the contributors page redirects to https://exercism.lol/contributing/contributors?track=bash, but if you go to https://exercism.lol/contributing/contributors directly, changing the track uses `track_slug` as the query string parameter.

**Comment by iHiD** [comment]
@kntsoriano:
- Use `track_slug` everywhere
- Update any links that point to this page.
