### ISSUE TITLE
[Page: Editor] Inconsistent tab size.

### ISSUE THREAD

**Issue by wischi-chr** [exercism/v3-beta#25]
I found this accidentally and am not even sure if one consider it a bug.

While solving a rust exercise and playing around with the setting "Tab enabled" I ended up submitting a file with different indentation styles (mixed spaces and tab) in the editor the file looks like this (Line 20 has tab indentation)

![image](https://user-images.githubusercontent.com/2495113/119183261-1f5b9380-ba74-11eb-8014-8907c3fab260.png)

And in the "Your iterations" tab it looked like this (Line 20):

![image](https://user-images.githubusercontent.com/2495113/119183381-4ca84180-ba74-11eb-833d-558d0fc8fa65.png)

IMHO both options are fine but they should be consistent.

**Comment by iHiD** [comment]
@ErikSchierboom Probably worth you taking a look at this but you might want @kntsoriano's input too.

**Comment by ErikSchierboom** [comment]
I've found that there are two issues here:

1. The configured language's tab size is not passed on to highlightjs.
2. Leading spaces or tabs are ignored (stripped).

You can see an example of that by going to https://exercism.lol/tracks/csharp/exercises/annalyns-infiltration/solutions/ErikSchierboom

The first line actually contains four leading spaces, which are not in the output.
The second line contains a tab, which uses a width of 8.

For the tab size, I've found that there is a `tabReplace` option, but that seems to be global: https://highlightjs.readthedocs.io/en/latest/api.html#configure-options

@joshgoebel Any idea how best to approach these issues?

**Comment by joshgoebel** [comment]
> For the tab size, I've found that there is a tabReplace option, but that seems to be global:

`tabReplace` is going away in v11, though it's easy to do via a plugin.  _Honestly we [Highlight.js] don't care about tab size._  The _best thing_ is to normalize the tabs to spaces before asking us to highlight the content.  It's possible to do this [with a plugin](https://github.com/highlightjs/highlight.js/issues/2874), or it's possible to do this entirely before it reaches us.

There is also CSS `tab-size` now https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size which might be a quicker solution to some of these problems.  IE, one could apply tab-size per language (say with a `.language-python` selector) to control the tab sizes inside the code using purely CSS.
