### ISSUE TITLE
[Track] When I join a track without a learning mode, I'm still in learning mode by default

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#250]
When I join a track that doesn't have learning mode, I'm still in learning mode by default and I can switch between learning mode and practice mode even through they don't differ at all. This should not be possible. All tracks without learning mode should be in practice mode without the option to switch, as long as there is no learning mode.

**Comment by iHiD** [comment]
See https://github.com/exercism/website/pull/1471
