### ISSUE TITLE
Automated feedback modal is unstyled

### ISSUE THREAD

**Issue by kntsoriano** [exercism/v3-beta#255]
When clicking the button in the mentor discussion, the modal that opens is unstyled.

![Screen Shot 2021-08-26 at 12 16 18 PM](https://user-images.githubusercontent.com/1901520/130899738-487e0607-2a18-4198-b73b-2b51df5a74fe.png)
![Screen Shot 2021-08-26 at 12 16 23 PM](https://user-images.githubusercontent.com/1901520/130899740-b5689d38-1833-4c0b-8f6f-eaa4e43bf0b5.png)

**Comment by iHiD** [comment]
`app/javascript/components/student/iterations-list/AnalyzerFeedback.tsx`

* Wrap the text above the <a> in `<p className="text-p-base mb-8">`
* Use proper external link helper

If that second bit doesn’t style it then style the link with

```.explanation a {
  @apply flex items-center;
  & .c-icon {
    height:16px;
    width:16px;
    @apply ml-8
  } 
}```

Inside `c-automated-feedback` in app/css/components/automated-feedback.css
