### ISSUE TITLE
Completing practice exercise modal is shit

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#273]
<img width="909" alt="Screenshot 2021-08-26 at 16 25 34" src="https://user-images.githubusercontent.com/286476/130991066-8987dc63-4aa1-4d6b-946b-69bf3d3e4b12.png">

@taiyab Can you 1-1 me what the correct thing is here pls?

**Comment by taiyab** [comment]
@iHiD 

No syllabus.

![image](https://user-images.githubusercontent.com/5337876/131260768-94efc68e-a4e5-4a64-8cf6-60acb222ae8b.png)

With syllabus.

![image](https://user-images.githubusercontent.com/5337876/131260777-68b9a2fa-7f7b-4769-97d7-f9a75d78b793.png)

Posted Figma link in Slack.
