### ISSUE TITLE
[Exercise] Iteration Component Blue Dot is Static

### ISSUE THREAD

**Issue by taiyab** [exercism/v3-beta#288]
The blue dot mechanism is static on the `Iteration` component.

It needs to only show when there is new analysis to look at, and maybe only for the most recent iteration on an exercise.

![image](https://user-images.githubusercontent.com/5337876/131134459-82ea722a-ad7d-4801-b6bb-b5bdfaed1ba4.png)

![image](https://user-images.githubusercontent.com/5337876/131134488-e2ec3b9a-6a01-44a7-8c08-b84b8d6321fa.png)

**Comment by iHiD** [comment]
We're taking it off for now. The blue dot works properly elsewhere for exercises, tracks, and solutions, but getting it working at the iteration level is a bit too hard for now.

@kntsoriano Assigning to you to do.
