### ISSUE TITLE
[Page: Concepts] [Rust] Unclear how to unlock more concepts

### ISSUE THREAD

**Issue by wischi-chr** [exercism/v3-beta#29]
I'm not sure how I can unlock integers for example. The graph I see at the moment, all the root elements are either done ("Enums Basic") or locked. Am I missing something or it the rust concept path not finished yet?

![image](https://user-images.githubusercontent.com/2495113/119201663-a66a3500-ba8f-11eb-95b9-3ca225a2c2b3.png)

**Comment by iHiD** [comment]
The Rust concept path isn't finished yet. I'm not sure it will be now for launch 🙁

**Comment by wischi-chr** [comment]
It looks like the unlocking mechanism works now. I guess because of the new "Introductory Functions"

![image](https://user-images.githubusercontent.com/2495113/125893441-4b180282-7e87-4b49-9384-982169e953d9.png)
