### ISSUE TITLE
[Exercise: Solutions] The share options dropdown is messed up with respect to css

### ISSUE THREAD

**Issue by ProProgrammer2504** [exercism/v3-beta#293]
![2021-08-27 (1)](https://user-images.githubusercontent.com/73734376/131159992-f6c0a5cd-f89c-42ca-b081-a08ebfdcb4dc.png)

**Comment by ProProgrammer2504** [comment]
Yes its fixed, closing this now

**Comment by iHiD** [comment]
Thanks :)
