### ISSUE TITLE
[Dashboard] "Discover more tracks"

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#298]
On the dashboard, there is this section that says "your tracks (3)" and below them there's a link that says "discover more tracks".

![Screen Shot 2021-08-27 at 19 16 51](https://user-images.githubusercontent.com/7852553/131164979-92faeeaf-127b-4ced-a047-5caaa081ce4d.png)

Both parts feel wrong to me. It suggests that I have only joined 3 tracks, but I have joined 55. "Discover more tracks" suggests that there are some tracks that I haven't joined, but I joined all of them already :).

The latter might not be worth fixing because who joins all tracks? But the former "(3)" might be worth fixing because people do join more than 3 tracks.

**Comment by iHiD** [comment]
Fixed in https://github.com/exercism/website/pull/1532
