### ISSUE TITLE
[Page: Profile] Closing a message / note reopens the notes on other tabs.

### ISSUE THREAD

**Issue by wischi-chr** [exercism/v3-beta#30]
A video is probably simpler to explain it:

https://user-images.githubusercontent.com/2495113/119202452-1a590d00-ba91-11eb-8ebc-fda103fcd7e6.mp4

**Comment by iHiD** [comment]
Interesting. Thanks. The state of those are currently being stored in your session not the db, but that shouldn't affect this. @kntsoriano Maybe we have some caching going on here causing this?

**Comment by wischi-chr** [comment]
If it doesn't happen for you and I can help you diagnose the issue please let me know.
