### ISSUE TITLE
Note blocks shouldn't be rendered using pre

### ISSUE THREAD

**Issue by glennj** [exercism/v3-beta#307]
I see this at https://exercism.lol/docs/community/being-a-good-community-member/the-words-that-we-use:
![image](https://user-images.githubusercontent.com/122470/131195404-c9446d41-c1ff-465c-8550-144b4982d772.png)

Clearly, having to scroll horizontally is not optimal.

**Comment by iHiD** [comment]
@glennj Thanks. This is a rendering issue in v3 so I've moved it here.

---

@ErikSchierboom I don't think we added these and some exercises (and this doc) rely on them :S

As a reminder, these are code-fences with the language set to `note` or some others that will be in the spec. Could you mutate these to be `<div class="c-textblock-note">` or `c-text-warning` etc pls. I'll then add styling.

---

@bethanyG I think you used these in exercises? Got an example of where one is that I can use to test things pls?

**Comment by ErikSchierboom** [comment]
@iHiD I don't see `note` being used in Python if I'm looking correctly. I do see Julia using `~~~~exercism/note`. Should we support both `note` and `exercism/note`?

**Comment by iHiD** [comment]
Oooh, good point. No, I believe we changed the spec to `exercism/note`, didn't we. So we should use that instead.

**Comment by iHiD** [comment]
(and update `note` to `exercism/note` anywhere it appears in the docs)

**Comment by ErikSchierboom** [comment]
Sure. Will do

**Comment by ErikSchierboom** [comment]
@iHiD PR has been updated

**Comment by ErikSchierboom** [comment]
And a [docs PR](https://github.com/exercism/docs/pull/213) has also been created.

**Comment by glennj** [comment]
Fix is reflected in https://exercism.org/docs/community/being-a-good-community-member/the-words-that-we-use

Thanks to all!
