### ISSUE TITLE
[Page: Code of Conduct] Code of Conduct currently not reachable

### ISSUE THREAD

**Issue by wischi-chr** [exercism/v3-beta#31]
I just tried to join as a mentor for C# and followed the link to the code of conduct
https://exercism.lol/code-of-conduct

The page currently returns the following error:
![image](https://user-images.githubusercontent.com/2495113/119203129-a3bd0f00-ba92-11eb-9d9e-63bcee6fd8ea.png)

`Rails.root: /opt/exercism/website/current` _(stack trace for copy-paste)_

**Comment by iHiD** [comment]
That page current isn't [in scope](https://github.com/exercism/v3-beta#pagesflows-ready-for-testing) 🙂
