### ISSUE TITLE
CLI Invalid Character

### ISSUE THREAD

**Issue by pertrai1** [exercism/v3-beta#310]
Hi, I wanted to try out the freelancer-rates exercise locally rather than in the editor, but I got this response when I tried to download from cli:

```
$ exercism download --exercise=freelancer-rates --track=javascript
Error: failed to parse API error response: invalid character '<' looking for beginning of value
```

My laptop is Windows 10 Home version 20H2

![exercism-cli-error](https://user-images.githubusercontent.com/442374/131225407-5d2a45c0-4192-44de-a76c-26f717a04a9c.jpg)

**Comment by angelikatyborska** [comment]
Did you update your CLI settings to use exercism.lol's API base URL and your secret token?

"invalid character '<'" sounds like a HTML response when a JSON response was expected. My blind guess would be cause your API config still points to exercism.io and that website is currently down 🙂.

FYI after the official launch you would need to change the configuration again if you do change it to use exercism.lol.

**Comment by pertrai1** [comment]
@angelikatyborska, great catch. Thank you for the quick response.
