### ISSUE TITLE
Browser Tab Title??

### ISSUE THREAD

**Issue by pertrai1** [exercism/v3-beta#312]
Seems like the html title could be more descriptive. Not sure if this is known and/or an issue.

![exercism-page-title](https://user-images.githubusercontent.com/442374/131225536-7a2c3536-90fd-432a-ab22-fe2370f6e1ee.jpg)

**Comment by iHiD** [comment]
Thanks for reporting. Closing as duplicate of https://github.com/exercism/v3-beta/issues/188
