### ISSUE TITLE
Most modals should have a close button

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#316]
We’re going to add a close button to most modals (it’ll be like a cross at the top right - @taiyab  hasn't designed it yet). 

We’ll need to add a option to `<Modal>` of `closeButton`. If it's `true` then it should add the button, which should close the modal. It can default to `false`. Pop a PR together with a button as close to the top of the modal (as in the HTML hierarchy) as you can and then I'll style it.

**Comment by taiyab** [comment]
![image](https://user-images.githubusercontent.com/5337876/131260871-ddc065de-4be6-4024-83a6-9d9e6acd4d97.png)

Figma link in Slack.
