### ISSUE TITLE
Add button to delete public profile.

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#319]
Easiest to put this into settings?

**Comment by taiyab** [comment]
Figma link sent in Slack.

**Comment by iHiD** [comment]
@kntsoriano 
<img width="503" alt="Screenshot 2021-08-29 at 23 00 23" src="https://user-images.githubusercontent.com/286476/131266692-b98694d5-8003-48ab-ab83-6ce500748212.png">


- Add button to settings page to delete your profile. 
- It has a generic confirmation box. 
- Use the request at `DELETE api/profiles`. 
- You can do `profile.destroy` in the controller.
