### ISSUE TITLE
Removing all the solutions from exercises

### ISSUE THREAD

**Issue by ProProgrammer2504** [exercism/v3-beta#332]
Creating this just so that you don't forget it before the launch.

**Comment by iHiD** [comment]
Already done. Thanks :)

**Comment by iHiD** [comment]
(Updates are no longer syncing to `.lol` btw)

**Comment by iHiD** [comment]
Thank you again for all your help. You should come join our slack. If you email me at jeremy@exercism.io, I'll send you a link :)
