### ISSUE TITLE
[Page: Iterations] Unclear meaning of the pen and paper icon with a counter

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#34]
When I look at my iterations, I don't understand what this icon means:

<img width="1317" alt="Screen Shot 2021-05-22 at 10 56 48" src="https://user-images.githubusercontent.com/7852553/119220880-e27fb300-baec-11eb-90de-0a515a34eee3.png">

I think it looks a bit like a comment icon, but I know that there are no human comments on my solution. After a few minutes of thinking about it, I arrived at the conclusion that the icon means that there is one analyzer comment on my solution, but it wasn't very easy to make that connection. This is how the analyzer comments look like:

<img width="386" alt="Screen Shot 2021-05-22 at 11 01 33" src="https://user-images.githubusercontent.com/7852553/119221051-bfa1ce80-baed-11eb-9fab-4f9f13193d77.png">

It lacks the typical UI characteristics of a comment IMO, which are a stand-alone author name (here the author name is inside of a sentence) and a timestamp.

Anyway, my point is not that the analyzer comments need a redesign, I just wanted to share my thought process :) but maybe this icon needs a tooltip with an explanation?

**Comment by iHiD** [comment]
Thanks 🙂 

I think changing the icon in the header to be the robot would probably help lots. And then also adding the tooltip too :)

**Comment by iHiD** [comment]
I've changed it to this for now. @taiyab We might want to think about how we could make this clearer, maybe we don't have the three icons and just one icon with three numbers? The tooltip will help too.

<img width="1413" alt="Screenshot 2021-05-22 at 14 31 47" src="https://user-images.githubusercontent.com/286476/119228342-79a73380-bb0a-11eb-8698-7ad3cf6636a1.png">

**Comment by taiyab** [comment]
@iHiD 

![image](https://user-images.githubusercontent.com/5337876/119508635-cb98c500-bd67-11eb-9b2e-721e316d4d36.png)

**Comment by iHiD** [comment]
Happy for this to be closed now @angelikatyborska ?

**Comment by angelikatyborska** [comment]
Yes, the robot icon is much better 👍
