### ISSUE TITLE
[Your Journey] Deal with common edge cases

### ISSUE THREAD

**Issue by taiyab** [exercism/v3-beta#341]
We need to deal with no mentoring (and probably no contribution) states better on Your Journey.

![image](https://user-images.githubusercontent.com/5337876/131507532-05961143-166f-4144-a001-b8f50294b082.png)

**Comment by taiyab** [comment]
Done a few zero states and sent them over.

**Comment by iHiD** [comment]
<img width="666" alt="Screenshot 2021-09-01 at 04 54 56" src="https://user-images.githubusercontent.com/286476/131609224-2ea86943-911e-4640-9c2d-66e3963c2fc6.png">

@kntsoriano Pop these two blocks if there is no mentoring or no contributions.
