### ISSUE TITLE
Proofread and update text

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-beta#342]
On the contributing page, the "Proofread and update" task type's description states:

> We’ll teach you how to use Git and GitHub to submit your first pull request.

We could consider replacing "teach you how to use" with "help you with", as I wouldn't want people thinking they're getting a Git/Github course from us :)

**Comment by iHiD** [comment]
Agreed. Can you update pls.

**Comment by ErikSchierboom** [comment]
https://github.com/exercism/website/pull/1650/ opened.
