### ISSUE TITLE
[Donate] Donate bar needs fixing 

### ISSUE THREAD

**Issue by taiyab** [exercism/v3-beta#344]
![image](https://user-images.githubusercontent.com/5337876/131510879-6ed1728e-6fa6-4dd2-9505-ea7713ec0a71.png)

**Comment by iHiD** [comment]
What's wrong with it?

**Comment by taiyab** [comment]
@iHiD 
![image](https://user-images.githubusercontent.com/5337876/131520009-43c94f3b-19b9-4edb-91bc-ed0c3a4aa073.png)

Sorry, here's a better screenshot.

**Comment by iHiD** [comment]
:+1: Deploying.
