### ISSUE TITLE
Exercise iterations page has error

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-beta#347]
If I go to one of my exercise's iterations (tracks/csharp/exercises/robot-name/iterations):

![image](https://user-images.githubusercontent.com/135246/131512890-08836ca3-bea8-4755-9f1c-08cec2543c1f.png)

I get an error:

![image](https://user-images.githubusercontent.com/135246/131513097-ef55acf1-57a4-4afb-945e-646d2eb870b2.png)

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/1619. Closing as duplicate of https://github.com/exercism/website/issues/1617
