### ISSUE TITLE
Bash two-fer community solutions contain other tracks

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-beta#350]
This might be just some weirdness in the data, but the bash track's two-fer community solutions look like they contain a lot of solutions that are _not_ bash. I can't find this issue in other tracks (C#, F# or Ruby).

![image](https://user-images.githubusercontent.com/135246/131520376-02ce3c3b-39b8-49f8-abb3-668dbf68a07f.png)

**Comment by iHiD** [comment]
Funky bug.

**Comment by angelikatyborska** [comment]
Not only they're not bash, some of they are even not two-fer (e.g. bottom right corner is hamming). But when you click to them, they lead to bash solution so I'm thinking just the snippet is wrong?

**Comment by iHiD** [comment]
Most are done but I need to do a few more of these.

**Comment by iHiD** [comment]
Done!
