### ISSUE TITLE
See what's changed is broken for Ruby two-fer

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-beta#351]
Clicking on the "See what's changed" on my Ruby two-fer solutions gives me:

![image](https://user-images.githubusercontent.com/135246/131521878-57746d69-47ec-4bad-8a19-45c4d74a2bd8.png)

**Comment by angelikatyborska** [comment]
I got the same for my Elixir Bob.

**Comment by iHiD** [comment]
:+1:

Note to self: Needs this running once the DB has less going on:
```
 UPDATE `solutions` INNER JOIN `exercises` ON `exercises`.`id` = `solutions`.`exercise_id` SET solutions.git_slug = exercises.slug,            solutions.git_sha = exercises.git_sha,            solutions.git_important_files_hash = exercises.git_important_files_hash;```

**Comment by iHiD** [comment]
@angelikatyborska @ErikSchierboom I think this should be fixed. Please reopen if it's not.
