### ISSUE TITLE
[CLI Wizard] Final Link to "Choose an Issue from Your Dashboard" Goes to Old Site 

### ISSUE THREAD

**Issue by BethanyG** [exercism/v3-beta#357]
Apologies, I wasn't able to grab a screenshot, and the wizard is no longer available to me via the website.

On the final message/step, there is a link [choose an issue from your dashboard].  It currently links to 'exercism.io'.

**Comment by iHiD** [comment]
@kntsoriano Could you check the walkthrough for any incorrect legacy links pls.
