### ISSUE TITLE
[Page: Editor] Rust test runner crashes

### ISSUE THREAD

**Issue by joshiraez** [exercism/v3-beta#38]
The test runner worked fine for Hello World, but for this one https://exercism.lol/tracks/rust/exercises/leap/edit the test runner will crash even when returning a simple `true`.

Unsure if the test running is part of the editor... I tried looking if there was a list of tracks being tested or if the test runner was part of the editor but didn't find anything specific

**Comment by iHiD** [comment]
Could you define "crashes" please?

**Comment by RoelofWobben** [comment]
you will see this message : 

``` 
An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.

Please check your code, and if nothing seems to be wrong, try running the tests again.
```

**Comment by iHiD** [comment]
Try again now pls?

**Comment by RoelofWobben** [comment]
For me no problems anymore

**Comment by iHiD** [comment]
Thanks :)

**Comment by joshiraez** [comment]
@RoelofWobben yes is the problem you said, and seem to be fixed now ^^
