### ISSUE TITLE
If tests fail and I try and rerun I get this message

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#39]
<img width="833" alt="Screenshot 2021-05-26 at 14 20 16" src="https://user-images.githubusercontent.com/286476/119666752-8e970600-be2d-11eb-8a32-76532bbdd946.png">

@kntsoriano I think this check and message is legacy now and should be removed?

**Comment by kntsoriano** [comment]
@iHiD Oh, this message is still from the API. Our API does not accept rerunning still.

**Comment by kntsoriano** [comment]
@iHiD This is a backend issue. Our API should allow rerunnning if the last submission's tests have failed / errored.
