### ISSUE TITLE
Sometimes the editor LHS ends up blank due to some issue with local storage

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#40]
https://www.loom.com/share/8b6355a0584a468e9f28ce085c8f2d5c

(cc @joshgoebel - this is what you also reported)

**Comment by joshgoebel** [comment]
More specifically (if it's helpful):

<img width="911" alt="Screen Shot 2021-05-28 at 3 42 38 PM" src="https://user-images.githubusercontent.com/6473/120034702-75c45700-bfcb-11eb-84f9-a5bb773287c5.png">
