### ISSUE TITLE
[Page: Track / Exercises] Exercise Dupe Bug

### ISSUE THREAD

**Issue by taiyab** [exercism/v3-beta#47]
https://www.loom.com/share/6595f4cdde4945ca9105605629db2b9e

**Comment by iHiD** [comment]
Thanks 🙂 

I believe this is down to @JoshGoebel having changed the uuid of TwoFer after adding the exercise to the config, so the website has multiple versions of TwoFer. Once we do the next ETL, this should go away, but I'll leave it open until then so we can confirm. If either you or Josh see the problem still after that, then it's a bug my end :)

**Comment by joshgoebel** [comment]
I've seen the problem before that and also assumed it was a data issue. :)
