### ISSUE TITLE
No feedback when clicking .c-copy-text-to-clipboard button

### ISSUE THREAD

**Issue by axtens** [exercism/v3-beta#49]
```html
<button type="button" class="c-copy-text-to-clipboard " aria-label="Copy &quot;exercism download --exercise=bob --track=wren&quot; to the cliboard"><div class="text">exercism download --exercise=bob --track=wren</div><img src="https://exercism-assets-staging.s3.eu-west-2.amazonaws.com/packs/media/images/icons/clipboard-a14bc00a6ce65fbe85a1f8d6f58e8faa.svg" alt="Copy to clipboard" class="c-icon"></button>
```
Is this actually working? It may be but I can't tell.

Running Chrome Version 91.0.4472.77 (Official Build) (64-bit) on Ubuntu Linux

**Comment by iHiD** [comment]
@taiyab When you get here, here's one possible idea: https://www.loom.com/share/a2f8de5591d847acbc63fc66a2bfb9bf

**Comment by taiyab** [comment]
![image](https://user-images.githubusercontent.com/5337876/122541578-af640d00-d021-11eb-941c-23d56688a1f8.png)

Something like this might work.
