### ISSUE TITLE
[Page: Exercise Community Solutions] "Concept Exercise" isn't a tag

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#5]
<img width="443" alt="Screenshot 2021-05-14 at 14 58 00" src="https://user-images.githubusercontent.com/286476/118281108-c82e4f80-b4c4-11eb-9282-da150dd18bcc.png">

**Comment by angelikatyborska** [comment]
Fixed 🎉 

![Screen Shot 2021-08-21 at 17 37 36](https://user-images.githubusercontent.com/7852553/130327138-044755cb-bbe6-4193-8700-a6ffee71efa3.png)

**Comment by iHiD** [comment]
Thanks!
