### ISSUE TITLE
[Track/Concepts] Deprecated exercises show on tooltips

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#55]
<img width="684" alt="Screenshot 2021-06-15 at 19 51 58" src="https://user-images.githubusercontent.com/286476/122107600-28d9e080-ce13-11eb-87de-a904cc5b89cb.png">

**Comment by BethanyG** [comment]
Adding this here.  It's showing on a a different page (https://exercism.lol/tracks/python/exercises/guidos-gorgeous-lasagna), but I am assuming it is related to the data/loading shown above. If it isn't, let me know and I can log a separate issue.

 `Trinary` below is a deprecated exercise -- but it is displaying in the "unlocked" list on the `Guido's Gorgeous Lasagna` details page:

![image](https://user-images.githubusercontent.com/5923094/122434443-f54ea180-cf4b-11eb-9794-770cee48ccd6.png)

**Comment by angelikatyborska** [comment]
I also want to add that deprecated concept exercises show up on the exercise list. I don't know if I should create a separate issue or if it counts here:

Exercise config: https://github.com/exercism/elixir/blob/967530f60e55a0f2e3a226cf1a5944f863428e4b/config.json#L369-L374

<img width="1356" alt="Screen Shot 2021-06-27 at 10 56 37" src="https://user-images.githubusercontent.com/7852553/123538808-c3e98900-d736-11eb-981f-5a02e2f0b3aa.png">

**Comment by iHiD** [comment]
Thanks for this. If you see any other places where these appear, please add them as comments. @ErikSchierboom will add a checklist to this and work through them :)

**Comment by ErikSchierboom** [comment]
These are the places that have been identified to mistakenly show deprecated exercises:

- [ ] Concept map 
- [ ] Unlocked list on exercise details page
- [ ] Exercise list
