### ISSUE TITLE
[Track/Concepts] Exercises with Update Warning Show in Syllabus with Blank Tooltips

### ISSUE THREAD

**Issue by BethanyG** [exercism/v3-beta#56]
On Chrome/Mac Mojave, but suspect this is data and not display.

Was checking https://exercism.lol/tracks/python/concepts and noticed the following :
![image](https://user-images.githubusercontent.com/5923094/122109625-6cf8c100-cdd2-11eb-855e-a9bfc06c8cdb.png)

Clicked through to the exercise page (https://exercism.lol/tracks/python/exercises/simple-cipher)  and saw:

![image](https://user-images.githubusercontent.com/5923094/122109493-4c306b80-cdd2-11eb-810a-9b7e887ab9c3.png)

Updating the exercise then caused the tool tip to load and display:
![image](https://user-images.githubusercontent.com/5923094/122109802-a2051380-cdd2-11eb-986f-fe334468e2fd.png)

**Comment by iHiD** [comment]
@kntsoriano I've noticed that sometimes the data doesn't load too on these. Can you have a play on lol and work out what's causing it pls. The list of exercise dots on the main track page, or this concepts page, are both good places to look.
