### ISSUE TITLE
[Track/Exercises] All Exercises Flagged "Easy"

### ISSUE THREAD

**Issue by BethanyG** [exercism/v3-beta#57]
On  https://exercism.lol/tracks/python/exercises, and subsequently on the detail page https://exercism.lol/tracks/python/exercises/bank-account

This exercise is flagged "Easy", but in `config.json`, it is labelled as `difficulty 8`:

![image](https://user-images.githubusercontent.com/5923094/122133388-72b1cf00-cdf1-11eb-9475-415e748716e3.png)

_____
<img src="https://user-images.githubusercontent.com/5923094/122133416-7e04fa80-cdf1-11eb-8577-4d020bafa081.png" width="500">

Since the track only has one other exercise of higher difficulty (at 9), this exercise should be labeled "challenging" or "hard" or "high".

Here is another from the JS track (https://exercism.lol/tracks/javascript/exercises & https://exercism.lol/tracks/javascript/exercises/crypto-square) This exercise is labeled as "Easy" in the UI, but is `difficulty 9`, in `config.json`:

![image](https://user-images.githubusercontent.com/5923094/122133882-6a0dc880-cdf2-11eb-9b4d-0804499ce22f.png)

**Comment by ErikSchierboom** [comment]
Looks like we haven't gotten around to implementing difficulties: https://github.com/exercism/website/blob/f8c9393f1b8e986749aafff6bb770ce01eb0ed58/app/javascript/components/common/exercise-widget/Difficulty.tsx#L14

**Comment by BethanyG** [comment]
Ah!  Should we close this for now, since it's not a bug, but a TODO?

**Comment by ErikSchierboom** [comment]
I don't mind it being open as a reminder :)
