### ISSUE TITLE
[Tracks/Mentoring] Dead End after Leaving Mentor Testimonial on Wren Track

### ISSUE THREAD

**Issue by BethanyG** [exercism/v3-beta#58]
Steps:
1.  Went to : https://exercism.lol/tracks/wren/exercises/hello-world.
2.  Noticed there was feedback, clicked through to https://exercism.lol/tracks/wren/exercises/hello-world/mentor_discussions/fee73188f2a84ced8c2017b2f0a789ce, and left some more comments.
3.  Clicked `end conversation`.
4.  Rated the session "happy" and opted to leave feedback.
5.  Typed feedback comments and pressed `[submit]`

Got the following, and there is no (apparent) way back via navigation.....

![image](https://user-images.githubusercontent.com/5923094/122176401-65203780-ce39-11eb-87d3-192d8f8d8b91.png)

Not sure if this is track specific or not, since I haven't yet tried this flow anywhere but the Wren track.

A browser refresh "clears" the state, and returns me to:  https://exercism.lol/tracks/wren/exercises/hello-world/mentor_discussions/fee73188f2a84ced8c2017b2f0a789ce, with `ended` flagged:

![image](https://user-images.githubusercontent.com/5923094/122177141-2f2f8300-ce3a-11eb-9a52-5c43550e3f2e.png)

**Comment by iHiD** [comment]
Thanks for the details report! :) Mentor discussions are still out of scope atm, so I wouldn't expect things to all work properly. FYI, this is last major blocker to them moving into scope (the other things being the mentoring tab being finished).

I'll leave this open though and you can recheck for me once mentor discussions move into scope! :)
