### ISSUE TITLE
[Tracks/Exercises Mentor Discussion] Comments Preview Strips Bullets and Numbers

### ISSUE THREAD

**Issue by BethanyG** [exercism/v3-beta#59]
**Very Minor**  When making a comment during a mentoring discussion, typed a bulleted list to try it out:

![image](https://user-images.githubusercontent.com/5923094/122178374-5fc3ec80-ce3b-11eb-9d52-7b62409619bd.png)

Previewed the list, but no love:

![image](https://user-images.githubusercontent.com/5923094/122178435-70746280-ce3b-11eb-9f76-b00698e00fce.png)

However, the "sent" comment came out just fine:

![image](https://user-images.githubusercontent.com/5923094/122178560-884be680-ce3b-11eb-8010-b4de05b04e3f.png)

**Comment by angelikatyborska** [comment]
This one is fixed already
