### ISSUE TITLE
[Contributing/Tasks] Tasks without action look broken due to lack of icon

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#62]
Tasks that do not have an `x:action` label look broken because they do not have an icon.

I'm not 100% sure what's the best solution here. Get rid of the round border if there is no icon? Or introduce a placeholder icon? Maybe you already had a design for this corner case but it's not implemented yet?

<img width="1392" alt="Screen Shot 2021-06-20 at 13 29 43" src="https://user-images.githubusercontent.com/7852553/122672524-31903500-d1cc-11eb-84d0-a3cb7450b581.png">

**Comment by iHiD** [comment]
Thanks. I'd forgotten to add it. Fixed in https://github.com/exercism/website/pull/1143
