### ISSUE TITLE
[Journey/Badges] Badge filter broken

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#64]
This looks to me like the badge filter wasn't implemented at all, but maybe it works when you have more badges? I think from the gif it's clear that something is not as intended 🤔 

![2021-06-20 13 57 51](https://user-images.githubusercontent.com/7852553/122673259-df511300-d1cf-11eb-9105-418ecf731660.gif)

**Comment by angelikatyborska** [comment]
I see this UI element was deleted completely so I'm considering this bug resolved.

**Comment by iHiD** [comment]
Yeah - we will probably add a "rarity" dropdown at some point, but not a priority before launch :)
