### ISSUE TITLE
[Mentoring/Workspace] Comment count is always 0

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#65]
When I browse my finished mentoring sessions and also sessions waiting for the student, the icon with the comment always has a 0 next to it. By definition, each of those mentoring sessions must have had at least one comment from me, otherwise it wouldn't be a mentoring session. At first I thought maybe the count is supposed to be the number of comments from the student, but that also shouldn't always be 0, I have a lot of sessions with student comments.

<img width="1324" alt="Screen Shot 2021-06-20 at 14 30 56" src="https://user-images.githubusercontent.com/7852553/122674303-cbf47680-d1d4-11eb-80e2-92a246816898.png">

**Comment by kntsoriano** [comment]
@angelikatyborska Has this been fixed?

**Comment by angelikatyborska** [comment]
@kntsoriano no, I still see zeros on conversations that do have comments

**Comment by kntsoriano** [comment]
@angelikatyborska Thanks!

@iHiD Could this be an ETL issue? My list the correct number of comments.

**Comment by iHiD** [comment]
@kntsoriano Yes. I think so. I've added a TODO here: https://github.com/exercism/website/pull/579#issuecomment-907612910

@angelikatyborska I've run a script to populate values for you. Could you check if that's fixed it pls? If so, I'll mark this as fixed in next ETL.

**Comment by angelikatyborska** [comment]
@iHiD yes, the numbers are correct now, but on one of the randomly checked discussion (https://exercism.lol/mentoring/discussions/dbe71e20-a82c-11eb-b069-cd08bd9fe49b) I'm getting this error: https://github.com/exercism/website/issues/1193 (just FYI)

**Comment by iHiD** [comment]
This is done. Let me know if you see issues.
