### ISSUE TITLE
[Mentoring/Workspace] "Filter by student or exercise name" - filter by student doesn't work

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#66]
In the filtering options, it only works to filter by exercise name. There are no results when I type student names.

![2021-06-20 14 41 43](https://user-images.githubusercontent.com/7852553/122674506-d5caa980-d1d5-11eb-9329-cf74c47f276a.gif)

**Comment by iHiD** [comment]
Fixed in https://github.com/exercism/website/pull/1146 - thanks 🙂
