### ISSUE TITLE
[Mentoring/Workspace] Sort by oldest/recent first or student doesn't work

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#67]
I cannot sort my mentoring sessions by date or by student. Changing between those three sorting options doesn't seem to change anything. Sorting by exercise is the only sorting option that behaves in a way that I would expect.

<img width="1324" alt="Screen Shot 2021-06-20 at 14 38 14" src="https://user-images.githubusercontent.com/7852553/122674630-55f10f00-d1d6-11eb-9ae1-c82a8c0f8da9.png">
<img width="1324" alt="Screen Shot 2021-06-20 at 14 38 24" src="https://user-images.githubusercontent.com/7852553/122674631-57223c00-d1d6-11eb-8bbe-6b395e254018.png">

**Comment by iHiD** [comment]
Thanks 🙂  Fixed in https://github.com/exercism/website/pull/1145.

Couple of bugs here. 
1. The date sorting was actually working, but the date shown didn't correspond to the date sorted by.
2. "Student" wasn't done at all.
