### ISSUE TITLE
[Tracks list, Tracks list] Wrong exercise count

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#68]
The exercise count on the track list page looks suspicious to me for some tracks, e.g. it says that there are 0 CoffeeScript exercises. If I go to the external page, I see the same wrong number again at the top, but then at the bottom there's the correct number. This happens for many tracks.

Examples: Bash, CoffeeScript, CommonLips
<img width="1792" alt="Screen Shot 2021-06-23 at 17 52 01" src="https://user-images.githubusercontent.com/7852553/123129724-71fde600-d44c-11eb-8cfa-22ed75299d69.png">
<img width="1792" alt="Screen Shot 2021-06-23 at 17 52 17" src="https://user-images.githubusercontent.com/7852553/123129735-75916d00-d44c-11eb-9c92-368f3bfc7101.png">
<img width="1792" alt="Screen Shot 2021-06-23 at 17 52 30" src="https://user-images.githubusercontent.com/7852553/123129763-7a562100-d44c-11eb-8e63-a5dda9482ec4.png">

<img width="1792" alt="Screen Shot 2021-06-23 at 17 52 39" src="https://user-images.githubusercontent.com/7852553/123129777-7d511180-d44c-11eb-96e6-8d407107af91.png">

**Comment by iHiD** [comment]
Nice spot.

This is an ETL issue. I've updated things now to be correct (I think) and added a note to the ETL branch to fix this.

If you're happy that things are right now, could you close this pls :)
