### ISSUE TITLE
[Page: Editor] Collapsing code blocks - surprising button hit area

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#7]
In the editor, there are tiny carets next to some line numbers. They look like tiny buttons when you hover over them. My assumption was that clicking on them would collapse and expand code blocks. I was surprised that doesn't happen. Clicking on them seems to select text instead. I tested on 3 different tracks and 2 different browsers (FF and Chrome on mac). After 10 minutes of testing I realized that it is possible to collapse the code block, but you have to click next to the button, not on the button.

<img width="952" alt="Screen Shot 2021-05-15 at 08 42 57" src="https://user-images.githubusercontent.com/7852553/118351186-b8f9e100-b55a-11eb-9778-a6d396a31f15.png">

Here's a gif:

![2021-05-15 08 43 15](https://user-images.githubusercontent.com/7852553/118351192-c2834900-b55a-11eb-83f0-7af2793331f4.gif)

**Comment by iHiD** [comment]
Funky. Thanks :)

**Comment by angelikatyborska** [comment]
I think this was fixed by switching to CodeMirror.

**Comment by iHiD** [comment]
Yes! Thanks :)

**Comment by iHiD** [comment]
(This was one of the reason that got me thinking about changing - as it was proving so hard to style)
