### ISSUE TITLE
[Mentoring/Discussion] Cancel button in weird place

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#73]
![Uploading Screenshot 2021-06-24 at 21.30.52.png…]()

**Comment by angelikatyborska** [comment]
Jeremy's screenshot didn't finish uploading so here's mine:
![Screen Shot 2021-06-25 at 10 45 26](https://user-images.githubusercontent.com/7852553/123397233-7b996200-d5a2-11eb-8225-f9d0504763be.png)

**Comment by iHiD** [comment]
@angelikatyborska And check this one can be closed too pls? :)

**Comment by angelikatyborska** [comment]
Is the expected solution that there is no cancel button?

**Comment by iHiD** [comment]
The cancel button should only appear when the text is removed.

**Comment by angelikatyborska** [comment]
On a mentoring session in progress I have a cancel button that is always enabled (which makes sense to me as you need to click it to close the editor), but on a mentoring session that I want to start as a mentor, there is no cancel button. The send button also looks different, it doesn't have the icon.

![Screen Shot 2021-07-05 at 13 42 06](https://user-images.githubusercontent.com/7852553/124466301-cf702c00-dd96-11eb-9588-c5cf85ce1d71.png)

**Comment by iHiD** [comment]
@angelikatyborska Deploying a new version now.
