### ISSUE TITLE
[Mentoring/Discussion] Headings of lower levels have styling when writing, but not when saved

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#74]
I can include from `#` to `####` in the message I am writing. When I write it, it looks styled. When I save, only `#` has any distinct style.

![Screen Shot 2021-06-25 at 10 48 26](https://user-images.githubusercontent.com/7852553/123397759-1134f180-d5a3-11eb-8440-e9d80588dd0f.png)

![Screen Shot 2021-06-25 at 10 48 33](https://user-images.githubusercontent.com/7852553/123397765-142fe200-d5a3-11eb-8e6c-0c36587025cc.png)

**Comment by iHiD** [comment]
Should be fixed by https://github.com/exercism/website/pull/1157

**Comment by iHiD** [comment]
Pls reopen if that commit didn't fix it :)

**Comment by angelikatyborska** [comment]
Looks fixed! It just gets turned into a h6, which makes sense.

**Comment by angelikatyborska** [comment]
The do look the same between the preview and actual output now 👍. It's a bit weird that only the first two levels have any visible styling, but I understand why. It should be enough in the comments anyway.
