### ISSUE TITLE
[Mentoring/Discussion] "Unable to save post" when using `#####`

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#75]
When I attempt to add `#####` in my comment, I get this generic unstyled error. Note that the error calls the record a "post" but the user is writing a "comment".

![Screen Shot 2021-06-25 at 10 50 44](https://user-images.githubusercontent.com/7852553/123397945-4b9e8e80-d5a3-11eb-8def-f65918916929.png)

**Comment by iHiD** [comment]
Should be fixed by https://github.com/exercism/website/pull/1157

**Comment by iHiD** [comment]
Pls reopen if that commit didn't fix it :)

**Comment by angelikatyborska** [comment]
Looks fixed! It just gets turned into a h6, which makes sense.

**Comment by iHiD** [comment]
Great. Thanks :)
