### ISSUE TITLE
[Mentoring/Discussion] "Cancel" discards my whole comment without warning

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#76]
When I click "cancel", I lose everything I have written in the comment. This might be surprising to some users, and might also annoy those that clicked the button accidentally. That is exactly what happened to me the first time... I would like to propose that clicking this button should produce a warning similarly like on GitHub.

![2021-06-25 10 36 53](https://user-images.githubusercontent.com/7852553/123398441-d67f8900-d5a3-11eb-8533-cb61792ec3ab.gif)

![Screen Shot 2021-06-25 at 10 54 57](https://user-images.githubusercontent.com/7852553/123398435-d41d2f00-d5a3-11eb-9b14-7dc2c834b11d.png)

**Comment by iHiD** [comment]
@angelikatyborska Could you retest this now please?

**Comment by angelikatyborska** [comment]
Now that there is no cancel button, I can still accidentally lose my comment by closing the tab or refreshing the page. I don't know if you care about that... on GitHub, the comment gets saved so that I don't lose it if I refresh the page. A warning if the textarea is not empty could also work.

**Comment by iHiD** [comment]
Hmm, that's a bug then. It should be saved in localstorage. @kntsoriano?

**Comment by angelikatyborska** [comment]
It looks to me like the comment only gets saved after clicking "cancel", not as I type. And it doesn't get restored when I cancel and try to comment again, it only gets restored after I refresh the page.

![2021-07-05 13 35 01](https://user-images.githubusercontent.com/7852553/124465791-1ad60a80-dd96-11eb-890f-34116555d90c.gif)

About my comment:
> Now that there is no cancel button

There is no cancel button when writing the initial comment on the mentoring session (as a mentor starting to mentor). I can see that there is a cancel button when posting comments on a session that is in progress or already finished.

**Comment by iHiD** [comment]
OK, stuff isn't working as expected here. Thanks.

**Comment by iHiD** [comment]
@angelikatyborska Deploying a new version now.
