### ISSUE TITLE
[Mentoring/Discussion] Cannot edit first comment

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#78]
As a student, when I request mentoring, I can write a comment. Later, I am unable to edit this comment. This is confusing because my first comment looks exactly the same as all the following comments, so from this view's perspective, there is no explanation as to why this first comment is special and cannot be edited.

![2021-06-25 14 54 58](https://user-images.githubusercontent.com/7852553/123428305-f3c54f00-d5c5-11eb-927b-401b46f3aa14.gif)

**Comment by iHiD** [comment]
@kntsoriano How do you think we should do this?
