### ISSUE TITLE
[Page: External Track] A few tracks do not have a glow around their logo

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#8]
This bug was already mentioned by @iHiD on the call, but there's no issue for it yet, so I thought it will be helpful to create it.

On the track page, the big track logo should have a "glow" (drop-shadow). Example of a correct glow:

<img width="1303" alt="Screen Shot 2021-05-15 at 09 03 38" src="https://user-images.githubusercontent.com/7852553/118351497-a5e81080-b55c-11eb-9164-723d8b8450ca.png">

Those tracks are missing it:
- C#
- C++
- Delphi Pascal
- F#
- MIPS Assembly

Notes:
- I had to test this logged out so that I could also test tracks that I have joined. I'm assuming "External track" page means track page when you haven't joined the track.
- I wasn't able to test JavaScript's or Swift's glow because the track page, when not logged in, throws an error.
- R's "glow" is almost impossible to see because it's too similar to the background color, but it's there.

Example lack of "glow":

<img width="1303" alt="Screen Shot 2021-05-15 at 09 07 03" src="https://user-images.githubusercontent.com/7852553/118351712-bc429c00-b55d-11eb-834c-201fc1d3382a.png">

Possible cause - CSS variable not set:

<img width="440" alt="Screen Shot 2021-05-15 at 09 07 50" src="https://user-images.githubusercontent.com/7852553/118351721-cebcd580-b55d-11eb-9ff8-7f5aee8120af.png">

**Comment by iHiD** [comment]
@angelikatyborska Thank you.

@taiyab Could you please provide me with colours for the ones that are missing. I think the easiest place might actually be the [docs page](http://exercism.lol/docs/tracks), although Angelika's testing per track has highlighted that we might want to change R too. We also need to separate the colours of the "C" family of languages as colour is the main way of distinguishing the logos.

**Comment by taiyab** [comment]
@iHiD 

https://github.com/exercism/website-icons/pull/53

New color variable for R: #57575E

C: #138C94 
C++: #821394 
Delphi Pascal: #F32735 
F#: #30B9DB
MIPS Assembly: #6241C0

**Comment by iHiD** [comment]
Updated. Deploying now. Thanks both.

**Comment by angelikatyborska** [comment]
Was this actually deployed? I'm still not seeing the glow on C#, C++ etc.

**Comment by iHiD** [comment]
Good spot.

Yes, it was. There's a second bug. I'll fix later. Thanks :)

**Comment by angelikatyborska** [comment]
I rechecked this again and Delphi is still missing the glow. The cause is a typo in the stylesheet 😁 
<img width="265" alt="Screen Shot 2021-08-21 at 17 27 45" src="https://user-images.githubusercontent.com/7852553/130326851-c8952a08-66fd-4462-9697-72c5a162dc23.png">
