### ISSUE TITLE
[Mentoring/Discussion] "Full screen" when editing a comment doesn't do much

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#80]
![2021-06-25 17 57 46](https://user-images.githubusercontent.com/7852553/123452703-f97b5e80-d5de-11eb-9084-97aec2c847ea.gif)

**Comment by iHiD** [comment]
Thanks. I'm not even sure we want that feature (it's built into the editor). What do you think?

**Comment by angelikatyborska** [comment]
I think my preferred solution would be to get rid of the full screen feature, but instead make the two columns resizable like they are in the editor when solving an exercise. This would allow me to expand the comment section in case I need to write or read something that has long horizontal content.

**Comment by iHiD** [comment]
They will be resizable, so that works.

**Comment by iHiD** [comment]
@kntsoriano Can you:
- [ ] Remove this full-screen option.
- [ ] Add the option to resize the two sides pls. Save their previous sizing in local storage. You've done this in the editor and I think the same code can be applied here. If you're unsure on the best way to do it with the CSS (e.g. if it's weird here compared to the editor) please let me know and I'll take a look first.
