### ISSUE TITLE
[Navigation] Notification dropdowns do not open after using navigation

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#82]
When I refresh the page, the notification dropdowns work. After I use the top navigation to change pages, they don't open anymore. I have to refresh the page.

![2021-06-25 18 30 37](https://user-images.githubusercontent.com/7852553/123457596-5cbbbf80-d5e4-11eb-8b52-6779f062ea17.gif)

**Comment by iHiD** [comment]
This is still broken @kntsoriano: https://www.loom.com/share/e44767f2ce504a7cb435844e3768db2b

**Comment by angelikatyborska** [comment]
I can confirm that the issue still appears, but to me it appears only sometimes, and only for the bell icon, not reputation 🤔

**Comment by iHiD** [comment]
@angelikatyborska This is deploying. Could you check in like 30mins from now to see if it's better pls? I'll do the same.

**Comment by angelikatyborska** [comment]
@iHiD It's not better, the bell dropdown still sometimes stops opening after navigating

**Comment by iHiD** [comment]
Sigh. @kntsoriano - reopening.

**Comment by iHiD** [comment]
@kntsoriano When clicking, the button is working, but the contents of the dropdown seem to be empty:

<img width="771" alt="Screenshot 2021-07-05 at 14 13 42" src="https://user-images.githubusercontent.com/286476/124476816-368fdf80-dd9b-11eb-8e1b-b49533b34a33.png">

**Comment by iHiD** [comment]
@kntsoriano Looking at the code, I think we're getting to this `null` here: https://github.com/exercism/website/blob/main/app/javascript/components/dropdowns/Notifications.tsx#L72

So two options:
1. If we can get there, we should be refetching the data. ie if `data` is null/undefined and `loading` is false, then we should change loading to true and refetch
2. We could also raise an exception there with some sort of internal state, and deploy that so at least then we can get some internal logging of what's going on.

**Comment by iHiD** [comment]
@kntsoriano Some further info from Angelika:

I think it has something to do with this request:
https://exercism.lol/api/v2/notifications?per=5
My observations about it:
1. after a page reload, this request is done once on every page I visit for the first time and it gets cached for a while, so when I switch between tracks <-> dashboard constantly, there are two requests, and then nothing for a while, and then after a while (1min? 30s?) the request is done again when switching the page
2. if the bell button breaks after a request to notifications?per=5 it remains broken at least until the next request to notifications?per=5
3. if the bell button works, it remains working at least until the next request to notifications?per=5

**Comment by iHiD** [comment]
We think this is fixed now, @angelikatyborska. Could you see if you can reproduce pls?

**Comment by angelikatyborska** [comment]
@iHiD I confirm that the problem was solved

**Comment by iHiD** [comment]
Great! :)
