### ISSUE TITLE
[Mentoring/Discussion] focus not in comment box after clicking 'add comment'

### ISSUE THREAD

**Issue by verdammelt** [exercism/v3-beta#89]
On Safari / MacOSX.

Expected:
1. click 'Add a comment'
2. start typing

This doesn't work - focus is not in comment box so typing goes "nowhere"

**Comment by iHiD** [comment]
@kntsoriano I think you might have already fixed this. If not, pls do.

**Comment by kntsoriano** [comment]
@iHiD So in Safari, the text box is focused, but the expanded markdown editor view is not looking well on Safari. I'm going to open another issue for it.
