### ISSUE TITLE
[Page: Editor] Test results change to "your tests timed out" after 60s

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#9]
Exactly 60s after pressing the "run tests" button, the real rests results disappear and instead the message "your tests timed out" appears. I managed to reproduce this on different tracks (Ruby, Elixir) on different exercises. I sat there with a stopwatch and timed it.

Here's a video of this happening: https://www.dropbox.com/s/d32x247m956nlhq/Screen%20Recording%202021-05-15%20at%2009.29.11.mov?dl=0

**Comment by iHiD** [comment]
@angelikatyborska Thanks :)

@kntsoriano I've been experiencing this too but hadn't understood the "exactly" 60s bit. Hopefully that gives you a good indication of what is happening.
