### ISSUE TITLE
[Exercise/Mentoring]: Student background is asked on each mentoring request

### ISSUE THREAD

**Issue by junedev** [exercism/v3-beta#93]
When requesting mentoring, this question shows every time.
```
What are you hoping to learn from this track?
Tell our mentors a little about your programming background and what you’re aiming to learn from Ruby.
```

This feels strange because my programming background and general aim does not really change from exercise to exercise.

The other question of course makes sense to have every time.

![image](https://user-images.githubusercontent.com/12543047/123469851-e45cfa80-d5f3-11eb-9bb2-1777ac9eb446.png)

**Comment by iHiD** [comment]
Thanks! Fixed by https://github.com/exercism/website/pull/1161 🙂
