### ISSUE TITLE
[Mentoring/Queue] Submisison count per language wrong after reload

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#94]
When I mentor multiple tracks, there is a language chooser on the left on the mentoring queue page. After I refresh the page, the first language is selected. Next to it, there is a number. That number is the total number of all submissions in the queue, not only for that language. After I use the language chooser to change the language, the number updates correctly.

Watch the behavior on the gif below (correct numbers are: total count - 26, Elixir - 23, Ruby - 3)

![2021-06-26 09 58 32](https://user-images.githubusercontent.com/7852553/123506638-8bc64580-d665-11eb-80c8-c6555f93371f.gif)

**Comment by iHiD** [comment]
@angelikatyborska Subtle! Nice work :)

@kntsoriano Another for you pls!
