### ISSUE TITLE
[Mentoring/Queue] `page` query param is not reset when filtering by language or exercise

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#95]
When I change the filters with the programming language or exercise, the "page" query param doesn't get reset to 1. This makes it look like the filtering is broken because there are no visible results, but the filters have numbers next to them that show how many results there should be.

![2021-06-26 10 10 39](https://user-images.githubusercontent.com/7852553/123506906-ead88a00-d666-11eb-8ae7-5c67567a9610.gif)

**Comment by iHiD** [comment]
@angelikatyborska Nice spot. Thanks! :) 

@kntsoriano One for you pls. Can you think through the other places where this is problematic too pls. There will be lots!
