### ISSUE TITLE
[Editor] F3 doesn't do anything

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#96]
In the editor, there are two shortcuts with F buttons - F2 to run the tests, and F3 to submit the solution. F2 works, F3 doesn't. Tested on FF on macOS, Chrome and macOS, and FF on Ubuntu - doesn't work in any of those.

**Comment by iHiD** [comment]
@kntsoriano Another for you :)

**Comment by kntsoriano** [comment]
I've tested and this seems to work. The focus must be on the text editor in order for this to work.

@angelikatyborska Can you give us steps to replicate this one? I'm thinking that the submit function gets called, but there's a guard within that function that prevents it from sending the post request. Thanks.

**Comment by ErikSchierboom** [comment]
I think I'd maybe prefer using a different F-key, as F3 is by default the "search on page" key which is very useful functionality to easily access.

**Comment by iHiD** [comment]
Yeah - we won't actually use F-keys for anything eventually. I can't get them on my laptop! :)
