### ISSUE TITLE
[Editor] "Run tests [F2]" in "results" tab looks clickable, but it's not

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#97]
In the "results" tab of an exercise without any test runs, there is a text that says "Run tests [F2] to check your code". When I hover over "Run tests [F2]", my cursor changes to a pointer, which suggests I could click it. But nothing happens when I click it. "F2" on its own also looks like a clickable button.

![2021-06-27 18 57 58](https://user-images.githubusercontent.com/7852553/123553174-f8326900-d779-11eb-85d6-efb1d0af3181.gif)

**Comment by iHiD** [comment]
@kntsoriano Can you make it clickable pls.

Also can you remove the text that flashes up next to "Run Tests" on the bottom when it's pressed please.
